-- ============================================
-- Mizero Inventory Hub - Database Backup
-- Generated: 6/20/2026, 10:30:20 AM
-- Database: mizero_inventory
-- Generated by: mugisha sting (admin@mizero.com)
-- ============================================

CREATE DATABASE IF NOT EXISTS `mizero_inventory`;
USE `mizero_inventory`;

SET FOREIGN_KEY_CHECKS = 0;

-- --------------------------------------------
-- Table: activity_logs
-- --------------------------------------------
DROP TABLE IF EXISTS `activity_logs`;
CREATE TABLE `activity_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `action` varchar(100) NOT NULL,
  `module` varchar(50) NOT NULL,
  `description` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_module` (`module`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `activity_logs` (`id`, `user_id`, `action`, `module`, `description`, `ip_address`, `created_at`) VALUES
(1, 1, 'system_reset', 'admin', 'All transactional data was wiped by mugisha sting (admin@mizero.com)', NULL, 'Sat Jun 20 2026 10:27:39 GMT+0200 (Central Africa Time)'),
(2, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sat Jun 20 2026 10:29:52 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: borrowings
-- --------------------------------------------
DROP TABLE IF EXISTS `borrowings`;
CREATE TABLE `borrowings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `borrower_name` varchar(200) NOT NULL,
  `borrower_phone` varchar(50) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_replacement_value` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_cost_at_time`) STORED,
  `borrow_date` date NOT NULL,
  `due_date` date NOT NULL,
  `status` enum('borrowed','returned','overdue','damaged','lost') NOT NULL DEFAULT 'borrowed',
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_status` (`status`),
  KEY `idx_due_date` (`due_date`),
  KEY `idx_borrower_name` (`borrower_name`),
  KEY `created_by` (`created_by`),
  KEY `idx_borrowings_borrower_name` (`borrower_name`(100)),
  KEY `idx_borrowings_item_id` (`item_id`),
  KEY `idx_borrowings_status` (`status`),
  KEY `idx_borrowings_borrow_date` (`borrow_date`),
  KEY `idx_borrowings_due_date` (`due_date`),
  KEY `idx_borrowings_created_at` (`created_at`),
  CONSTRAINT `borrowings_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `borrowings_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: budgets
-- --------------------------------------------
DROP TABLE IF EXISTS `budgets`;
CREATE TABLE `budgets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `department_id` int(11) NOT NULL,
  `fiscal_year` year(4) NOT NULL,
  `total_budget` decimal(14,2) NOT NULL DEFAULT 0.00,
  `description` varchar(255) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_department_fiscal` (`department_id`,`fiscal_year`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `budgets_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`),
  CONSTRAINT `budgets_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: customers
-- --------------------------------------------
DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `contact_person` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `customer_type` enum('individual','organization','school','government','ngo','other') DEFAULT 'individual',
  `tax_id` varchar(50) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_customers_name` (`name`),
  KEY `idx_customers_type` (`customer_type`),
  KEY `idx_customers_status` (`status`),
  KEY `idx_customers_deleted` (`deleted_at`),
  KEY `idx_customers_email` (`email`),
  KEY `idx_customers_phone` (`phone`),
  FULLTEXT KEY `ft_customers_search` (`name`,`contact_person`,`email`,`city`),
  CONSTRAINT `customers_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------
-- Table: damage_liabilities
-- --------------------------------------------
DROP TABLE IF EXISTS `damage_liabilities`;
CREATE TABLE `damage_liabilities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liability_type` enum('damaged','lost') NOT NULL DEFAULT 'damaged',
  `borrowing_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `item_name` varchar(200) NOT NULL,
  `item_sku` varchar(50) NOT NULL,
  `borrower_name` varchar(200) NOT NULL,
  `borrower_id` int(11) DEFAULT NULL COMMENT 'FK to users table if borrower is a system user',
  `borrower_phone` varchar(50) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `paid_quantity` int(11) NOT NULL DEFAULT 0,
  `remaining_quantity` int(11) GENERATED ALWAYS AS (`quantity` - `paid_quantity`) STORED,
  `unit_cost` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `liability_percentage` decimal(5,2) NOT NULL DEFAULT 50.00,
  `replacement_cost` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Full replacement cost before liability percentage (qty * unit_cost)',
  `liability_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Actual amount borrower owes (replacement_cost * liability_percentage/100)',
  `amount_paid` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Total monetary amount paid so far',
  `balance` decimal(14,2) GENERATED ALWAYS AS (`liability_amount` - `amount_paid`) STORED COMMENT 'Remaining balance (liability_amount - amount_paid)',
  `status` enum('pending','unpaid','partially_paid','paid','waived') NOT NULL DEFAULT 'pending',
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_borrower_name` (`borrower_name`),
  KEY `idx_borrowing_id` (`borrowing_id`),
  KEY `item_id` (`item_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_liability_borrower` (`borrower_id`),
  KEY `idx_liability_amount` (`liability_amount`),
  KEY `idx_liability_balance` (`balance`),
  KEY `idx_liability_paid` (`amount_paid`),
  KEY `idx_damage_liabilities_borrowing_id` (`borrowing_id`),
  KEY `idx_damage_liabilities_item_name` (`item_name`(100)),
  KEY `idx_damage_liabilities_borrower_name` (`borrower_name`(100)),
  KEY `idx_damage_liabilities_type` (`liability_type`),
  KEY `idx_damage_liabilities_status` (`status`),
  KEY `idx_damage_liabilities_created_at` (`created_at`),
  KEY `idx_damage_liabilities_liability_amount` (`liability_amount`),
  KEY `idx_damage_liabilities_amount_paid` (`amount_paid`),
  CONSTRAINT `damage_liabilities_ibfk_1` FOREIGN KEY (`borrowing_id`) REFERENCES `borrowings` (`id`),
  CONSTRAINT `damage_liabilities_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `damage_liabilities_ibfk_3` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_liability_borrower` FOREIGN KEY (`borrower_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: damage_payments
-- --------------------------------------------
DROP TABLE IF EXISTS `damage_payments`;
CREATE TABLE `damage_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liability_id` int(11) NOT NULL,
  `payment_quantity` int(11) NOT NULL,
  `unit_cost` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payment_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Actual payment amount',
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Explicit payment amount (not generated)',
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `paid_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_liability_id` (`liability_id`),
  KEY `idx_paid_at` (`paid_at`),
  KEY `created_by` (`created_by`),
  KEY `idx_damage_payments_liability_id` (`liability_id`),
  KEY `idx_damage_payments_paid_at` (`paid_at`),
  CONSTRAINT `damage_payments_ibfk_1` FOREIGN KEY (`liability_id`) REFERENCES `damage_liabilities` (`id`),
  CONSTRAINT `damage_payments_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: departments
-- --------------------------------------------
DROP TABLE IF EXISTS `departments`;
CREATE TABLE `departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `manager_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `departments` (`id`, `name`, `description`, `manager_id`, `created_at`, `updated_at`) VALUES
(1, 'General', 'General inventory department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(2, 'IT', 'Information Technology department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(3, 'Logistics', 'Logistics and transport department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(4, 'Finance', 'Finance and accounting department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: items
-- --------------------------------------------
DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sku` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `unit` varchar(50) NOT NULL DEFAULT 'pcs',
  `quantity` int(11) NOT NULL DEFAULT 0,
  `minimum_stock` int(11) NOT NULL DEFAULT 0,
  `unit_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` varchar(3) NOT NULL DEFAULT 'RWF',
  `item_type` enum('consumable','non-consumable') NOT NULL DEFAULT 'consumable',
  `department_id` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sku` (`sku`),
  KEY `idx_sku` (`sku`),
  KEY `idx_name` (`name`),
  KEY `idx_category` (`category`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_item_type` (`item_type`),
  KEY `idx_low_stock` (`quantity`,`minimum_stock`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `created_by` (`created_by`),
  KEY `idx_items_name` (`name`(100)),
  KEY `idx_items_sku` (`sku`),
  KEY `idx_items_department_id` (`department_id`),
  KEY `idx_items_category` (`category`),
  FULLTEXT KEY `ft_items_search` (`name`,`sku`,`category`,`description`),
  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `items_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=111 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: leftovers
-- --------------------------------------------
DROP TABLE IF EXISTS `leftovers`;
CREATE TABLE `leftovers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_out_id` int(11) NOT NULL,
  `returned_quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_value` decimal(14,2) GENERATED ALWAYS AS (`returned_quantity` * `unit_cost_at_time`) STORED,
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_stock_out_id` (`stock_out_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_leftovers_stock_out_id` (`stock_out_id`),
  KEY `idx_leftovers_created_at` (`created_at`),
  CONSTRAINT `leftovers_ibfk_1` FOREIGN KEY (`stock_out_id`) REFERENCES `stock_out` (`id`),
  CONSTRAINT `leftovers_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: notifications
-- --------------------------------------------
DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `module` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_read_user` (`is_read`,`user_id`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: requests
-- --------------------------------------------
DROP TABLE IF EXISTS `requests`;
CREATE TABLE `requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `requester_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `allocated_quantity` int(11) DEFAULT NULL,
  `justification` text DEFAULT NULL,
  `status` enum('pending','approved','rejected','allocated') DEFAULT 'pending',
  `reviewed_by` int(11) DEFAULT NULL,
  `reviewed_notes` text DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_requester_id` (`requester_id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `reviewed_by` (`reviewed_by`),
  KEY `idx_requests_requester_id` (`requester_id`),
  KEY `idx_requests_item_id` (`item_id`),
  KEY `idx_requests_status` (`status`),
  KEY `idx_requests_created_at` (`created_at`),
  CONSTRAINT `requests_ibfk_1` FOREIGN KEY (`requester_id`) REFERENCES `users` (`id`),
  CONSTRAINT `requests_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `requests_ibfk_3` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: returns
-- --------------------------------------------
DROP TABLE IF EXISTS `returns`;
CREATE TABLE `returns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `borrowing_id` int(11) NOT NULL,
  `returned_quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_value` decimal(14,2) GENERATED ALWAYS AS (`returned_quantity` * `unit_cost_at_time`) STORED,
  `item_condition` enum('good','damaged','lost') DEFAULT 'good',
  `notes` text DEFAULT NULL,
  `return_date` date NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_borrowing_id` (`borrowing_id`),
  KEY `idx_item_condition` (`item_condition`),
  KEY `idx_return_date` (`return_date`),
  KEY `created_by` (`created_by`),
  KEY `idx_returns_borrowing_id` (`borrowing_id`),
  KEY `idx_returns_return_date` (`return_date`),
  KEY `idx_returns_condition` (`item_condition`),
  KEY `idx_returns_created_at` (`created_at`),
  CONSTRAINT `returns_ibfk_1` FOREIGN KEY (`borrowing_id`) REFERENCES `borrowings` (`id`),
  CONSTRAINT `returns_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: roles
-- --------------------------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES
(1, 'super_admin', 'System owner with unrestricted access', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(2, 'admin', 'Operations manager with full inventory access', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(3, 'stock_manager', 'Warehouse/storekeeper managing daily operations', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(4, 'staff', 'Department employee requesting supplies', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: stock_adjustments
-- --------------------------------------------
DROP TABLE IF EXISTS `stock_adjustments`;
CREATE TABLE `stock_adjustments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `adjustment_type` enum('increase','decrease') NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_cost_at_time`) STORED,
  `reason` varchar(255) NOT NULL,
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_adjustment_type` (`adjustment_type`),
  KEY `idx_reason` (`reason`),
  KEY `created_by` (`created_by`),
  KEY `idx_stock_adjustments_date` (`created_at`),
  KEY `idx_stock_adjustments_item_id` (`item_id`),
  KEY `idx_stock_adjustments_type` (`adjustment_type`),
  CONSTRAINT `stock_adjustments_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `stock_adjustments_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: stock_in
-- --------------------------------------------
DROP TABLE IF EXISTS `stock_in`;
CREATE TABLE `stock_in` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_price`) STORED,
  `supplier` varchar(200) DEFAULT NULL,
  `supplier_type` varchar(50) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `department_id` int(11) DEFAULT NULL,
  `date` date NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_date` (`date`),
  KEY `idx_supplier` (`supplier`),
  KEY `created_by` (`created_by`),
  KEY `idx_stock_in_date` (`date`),
  KEY `idx_stock_in_item_id` (`item_id`),
  KEY `idx_stock_in_supplier` (`supplier`(100)),
  KEY `idx_stock_in_supplier_type` (`supplier_type`),
  KEY `idx_stock_in_reference` (`reference_number`),
  KEY `idx_stock_in_created_at` (`created_at`),
  KEY `idx_stock_in_department_id` (`department_id`),
  KEY `idx_stock_in_supplier_id` (`supplier_id`),
  CONSTRAINT `stock_in_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `stock_in_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `stock_in_ibfk_3` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: stock_out
-- --------------------------------------------
DROP TABLE IF EXISTS `stock_out`;
CREATE TABLE `stock_out` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_cost_at_time`) STORED,
  `recipient` varchar(200) NOT NULL,
  `department` varchar(100) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `date` date NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_date` (`date`),
  KEY `idx_recipient` (`recipient`),
  KEY `created_by` (`created_by`),
  KEY `idx_stock_out_date` (`date`),
  KEY `idx_stock_out_item_id` (`item_id`),
  KEY `idx_stock_out_recipient` (`recipient`(100)),
  KEY `idx_stock_out_department` (`department`),
  KEY `idx_stock_out_created_at` (`created_at`),
  CONSTRAINT `stock_out_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `stock_out_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: super_admin_audit_log
-- --------------------------------------------
DROP TABLE IF EXISTS `super_admin_audit_log`;
CREATE TABLE `super_admin_audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `actor_id` int(11) NOT NULL,
  `action` varchar(100) NOT NULL,
  `target_user_id` int(11) DEFAULT NULL,
  `details` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `status` enum('blocked','allowed') DEFAULT 'blocked',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_actor_id` (`actor_id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: suppliers
-- --------------------------------------------
DROP TABLE IF EXISTS `suppliers`;
CREATE TABLE `suppliers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `contact_person` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `supplier_type` enum('vendor','donor','school_garden','consignment','other') DEFAULT 'vendor',
  `tax_id` varchar(50) DEFAULT NULL,
  `payment_terms` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_suppliers_name` (`name`),
  KEY `idx_suppliers_type` (`supplier_type`),
  KEY `idx_suppliers_status` (`status`),
  KEY `idx_suppliers_deleted` (`deleted_at`),
  FULLTEXT KEY `ft_suppliers_search` (`name`,`contact_person`,`email`,`city`),
  CONSTRAINT `suppliers_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `suppliers` (`id`, `name`, `contact_person`, `email`, `phone`, `address`, `city`, `supplier_type`, `tax_id`, `payment_terms`, `notes`, `status`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Rwanda Revenue Authority (RRA) Supplies', 'Official Procurement', NULL, NULL, NULL, 'Kigali', 'vendor', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL),
(2, 'Rwanda Biomedical Center (RBC)', 'Logistics Office', NULL, NULL, NULL, 'Kigali', 'donor', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL),
(3, 'Akagera Business Group', 'Jean Baptiste', NULL, NULL, NULL, 'Kigali', 'vendor', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL),
(4, 'BK TecHouse', 'Patrick Mugisha', NULL, NULL, NULL, 'Kigali', 'vendor', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL),
(5, 'Rwanda Social Security Board (RSSB)', 'Procurement Dept', NULL, NULL, NULL, 'Kigali', 'vendor', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL),
(6, 'MINEDEC Supply Chain', 'School Programs', NULL, NULL, NULL, 'Kigali', 'school_garden', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL),
(7, 'Horizon Logistics', 'Alice Uwimana', NULL, NULL, NULL, 'Kigali', 'vendor', NULL, NULL, NULL, 'active', NULL, 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 15:44:33 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: user_departments
-- --------------------------------------------
DROP TABLE IF EXISTS `user_departments`;
CREATE TABLE `user_departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `department_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_department` (`user_id`,`department_id`),
  KEY `department_id` (`department_id`),
  CONSTRAINT `user_departments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_departments_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `user_departments` (`id`, `user_id`, `department_id`, `created_at`) VALUES
(1, 2, 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(2, 2, 2, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(3, 3, 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(4, 3, 3, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: users
-- --------------------------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role_id` int(11) NOT NULL,
  `department_id` int(11) DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `must_change_password` tinyint(1) NOT NULL DEFAULT 1,
  `last_login` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_email` (`email`),
  KEY `idx_role_id` (`role_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_status` (`status`),
  KEY `idx_users_must_change_password` (`must_change_password`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
  CONSTRAINT `users_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='When 1, the user must change their password on next login';

INSERT INTO `users` (`id`, `full_name`, `email`, `password`, `role_id`, `department_id`, `status`, `must_change_password`, `last_login`, `created_at`, `updated_at`) VALUES
(1, 'mugisha sting', 'admin@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 1, NULL, 'active', 0, 'Sat Jun 20 2026 10:29:52 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sat Jun 20 2026 10:29:52 GMT+0200 (Central Africa Time)'),
(2, 'John Manager', 'john@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 2, 1, 'active', 0, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 14:21:56 GMT+0200 (Central Africa Time)'),
(3, 'Stock Keeper', 'stock@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 3, 1, 'active', 0, 'Sun Jun 14 2026 10:50:24 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 14:21:56 GMT+0200 (Central Africa Time)'),
(4, 'Staff User', 'staff@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 4, NULL, 'active', 0, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 14:21:56 GMT+0200 (Central Africa Time)');

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- Backup complete
-- ============================================
