-- ============================================
-- Mizero Inventory Hub - Database Backup
-- Generated: 6/14/2026, 12:51:22 PM
-- Database: mizero_inventory
-- Generated by: mugisha sting (admin@mizero.com)
-- ============================================

CREATE DATABASE IF NOT EXISTS `mizero_inventory`;
USE `mizero_inventory`;

SET FOREIGN_KEY_CHECKS = 0;

-- --------------------------------------------
-- Table: activity_logs
-- --------------------------------------------
DROP TABLE IF EXISTS `activity_logs`;
CREATE TABLE `activity_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `action` varchar(100) NOT NULL,
  `module` varchar(50) NOT NULL,
  `description` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_module` (`module`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `activity_logs` (`id`, `user_id`, `action`, `module`, `description`, `ip_address`, `created_at`) VALUES
(1, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:16:55 GMT+0200 (Central Africa Time)'),
(2, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:17:06 GMT+0200 (Central Africa Time)'),
(3, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:21:14 GMT+0200 (Central Africa Time)'),
(4, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:25:17 GMT+0200 (Central Africa Time)'),
(5, 1, 'borrow', 'borrowing', 'Borrowed 8 of Filing Cabinet to IROT (replacement value: 960000.00)', NULL, 'Fri Jun 12 2026 21:25:41 GMT+0200 (Central Africa Time)'),
(6, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:25:56 GMT+0200 (Central Africa Time)'),
(7, 1, 'return', 'returns', 'Returned 7 of Filing Cabinet (good) @ 120000/unit', NULL, 'Fri Jun 12 2026 21:25:58 GMT+0200 (Central Africa Time)'),
(8, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Filing Cabinet as damaged (IROT) - liability: 120000.00', NULL, 'Fri Jun 12 2026 21:26:16 GMT+0200 (Central Africa Time)'),
(9, 1, 'damage_payment', 'damage_liabilities', 'Recorded payment of 1 units (120000.00) for liability #1 - IROT (Filing Cabinet). Status: paid', NULL, 'Fri Jun 12 2026 21:26:24 GMT+0200 (Central Africa Time)'),
(10, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:26:54 GMT+0200 (Central Africa Time)'),
(11, 1, 'borrow', 'borrowing', 'Borrowed 3 of Laptop Dell Latitude to MUGISHA (replacement value: 2550000.00)', NULL, 'Fri Jun 12 2026 21:27:28 GMT+0200 (Central Africa Time)'),
(12, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Laptop Dell Latitude as damaged (MUGISHA) - liability: 850000.00', NULL, 'Fri Jun 12 2026 21:27:58 GMT+0200 (Central Africa Time)'),
(13, 1, 'damage_payment', 'damage_liabilities', 'Recorded payment of 1 units (850000.00) for liability #2 - MUGISHA (Laptop Dell Latitude). Status: paid', NULL, 'Fri Jun 12 2026 21:28:35 GMT+0200 (Central Africa Time)'),
(14, 1, 'borrow', 'borrowing', 'Borrowed 2 of Projector Epson to FGHJ (replacement value: 1300000.00)', NULL, 'Fri Jun 12 2026 21:30:06 GMT+0200 (Central Africa Time)'),
(15, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Laptop Dell Latitude as damaged (MUGISHA) - liability: 850000.00', NULL, 'Fri Jun 12 2026 21:30:36 GMT+0200 (Central Africa Time)'),
(16, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Projector Epson as damaged (FGHJ) - liability: 650000.00', NULL, 'Fri Jun 12 2026 21:30:50 GMT+0200 (Central Africa Time)'),
(17, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:45:51 GMT+0200 (Central Africa Time)'),
(18, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:48:14 GMT+0200 (Central Africa Time)'),
(19, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:49:21 GMT+0200 (Central Africa Time)'),
(20, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 21:49:41 GMT+0200 (Central Africa Time)'),
(21, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Projector Epson as damaged (FGHJ) - liability: 650000.00', NULL, 'Fri Jun 12 2026 21:50:02 GMT+0200 (Central Africa Time)'),
(22, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Laptop Dell Latitude as damaged (MUGISHA) - liability: 850000.00', NULL, 'Fri Jun 12 2026 21:50:14 GMT+0200 (Central Africa Time)'),
(23, 1, 'borrow', 'borrowing', 'Borrowed 4 of Filing Cabinet to rue (replacement value: 480000.00)', NULL, 'Fri Jun 12 2026 21:51:20 GMT+0200 (Central Africa Time)'),
(24, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 22:02:14 GMT+0200 (Central Africa Time)'),
(25, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Fri Jun 12 2026 22:20:31 GMT+0200 (Central Africa Time)'),
(26, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Filing Cabinet as damaged (rue) - liability: 120000.00', NULL, 'Fri Jun 12 2026 22:22:18 GMT+0200 (Central Africa Time)'),
(27, 1, 'damage_report', 'damage_liabilities', 'Reported 1 of Filing Cabinet as damaged (rue) - liability: 120000.00', NULL, 'Fri Jun 12 2026 22:22:30 GMT+0200 (Central Africa Time)'),
(28, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Sun Jun 14 2026 09:12:48 GMT+0200 (Central Africa Time)'),
(29, 1, 'borrow', 'borrowing', 'Borrowed 10 of Laptop Dell Latitude to mugisha chris (replacement value: 8500000.00)', NULL, 'Sun Jun 14 2026 09:14:37 GMT+0200 (Central Africa Time)'),
(30, 1, 'return', 'returns', 'Returned 3 of Laptop Dell Latitude (Good condition) @ 850000/unit', NULL, 'Sun Jun 14 2026 09:14:59 GMT+0200 (Central Africa Time)'),
(31, 1, 'damage_report', 'damage_liabilities', 'Damaged 2 of Laptop Dell Latitude (mugisha chris) - liability: 850000.00 (50%)', NULL, 'Sun Jun 14 2026 09:15:23 GMT+0200 (Central Africa Time)'),
(32, 1, 'loss_report', 'damage_liabilities', 'Lost 1 of Laptop Dell Latitude (mugisha chris) - liability: 850000.00 (100%)', NULL, 'Sun Jun 14 2026 09:15:44 GMT+0200 (Central Africa Time)'),
(33, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Sun Jun 14 2026 09:46:06 GMT+0200 (Central Africa Time)'),
(34, 1, 'damage_report', 'damage_liabilities', 'Damaged 1 of Laptop Dell Latitude (mugisha chris) - liability: 425000.00 (50%)', NULL, 'Sun Jun 14 2026 09:46:48 GMT+0200 (Central Africa Time)'),
(35, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Sun Jun 14 2026 09:55:51 GMT+0200 (Central Africa Time)'),
(36, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 425000.00 for damaged liability #11 - mugisha chris (Laptop Dell Latitude). Status: paid', NULL, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(37, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 850000.00 for lost liability #10 - mugisha chris (Laptop Dell Latitude). Status: paid', NULL, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(38, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 850000.00 for damaged liability #9 - mugisha chris (Laptop Dell Latitude). Status: paid', NULL, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(39, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 120000.00 for damaged liability #8 - rue (Filing Cabinet). Status: paid', NULL, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(40, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 120000.00 for damaged liability #7 - rue (Filing Cabinet). Status: paid', NULL, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(41, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 850000.00 for damaged liability #6 - MUGISHA (Laptop Dell Latitude). Status: paid', NULL, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(42, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 650000.00 for damaged liability #5 - FGHJ (Projector Epson). Status: paid', NULL, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(43, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 650000.00 for damaged liability #4 - FGHJ (Projector Epson). Status: paid', NULL, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(44, 1, 'liability_payment', 'damage_liabilities', 'Recorded payment of 850000.00 for damaged liability #3 - MUGISHA (Laptop Dell Latitude). Status: paid', NULL, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(45, 1, 'login', 'auth', 'User Super Admin logged in', NULL, 'Sun Jun 14 2026 10:14:54 GMT+0200 (Central Africa Time)'),
(46, 1, 'update_profile', 'auth', 'User updated their profile', NULL, 'Sun Jun 14 2026 10:17:19 GMT+0200 (Central Africa Time)'),
(47, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:17:25 GMT+0200 (Central Africa Time)'),
(48, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:24:56 GMT+0200 (Central Africa Time)'),
(49, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:29:34 GMT+0200 (Central Africa Time)'),
(50, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:30:32 GMT+0200 (Central Africa Time)');
INSERT INTO `activity_logs` (`id`, `user_id`, `action`, `module`, `description`, `ip_address`, `created_at`) VALUES
(51, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:31:11 GMT+0200 (Central Africa Time)'),
(52, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:31:32 GMT+0200 (Central Africa Time)'),
(53, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:32:57 GMT+0200 (Central Africa Time)'),
(54, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:39:46 GMT+0200 (Central Africa Time)'),
(55, 1, 'stock_in', 'inventory', 'Stock in: 12 of Office Paper A4 @ 2146/RWF', NULL, 'Sun Jun 14 2026 10:40:50 GMT+0200 (Central Africa Time)'),
(56, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:43:48 GMT+0200 (Central Africa Time)'),
(57, 3, 'login', 'auth', 'User Stock Keeper logged in', NULL, 'Sun Jun 14 2026 10:43:48 GMT+0200 (Central Africa Time)'),
(58, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:48:21 GMT+0200 (Central Africa Time)'),
(59, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 10:50:24 GMT+0200 (Central Africa Time)'),
(60, 3, 'login', 'auth', 'User Stock Keeper logged in', NULL, 'Sun Jun 14 2026 10:50:24 GMT+0200 (Central Africa Time)'),
(61, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 11:04:12 GMT+0200 (Central Africa Time)'),
(62, 1, 'stock_out', 'inventory', 'Stock out: 5 of Stapler to loypr (COGS: 42500.00, Margin: 17500.00)', NULL, 'Sun Jun 14 2026 11:05:22 GMT+0200 (Central Africa Time)'),
(63, 1, 'leftover_return', 'inventory', 'Returned unused stock: 2 of Stapler (value: 17000.00)', NULL, 'Sun Jun 14 2026 11:09:35 GMT+0200 (Central Africa Time)'),
(64, 1, 'leftover_return', 'inventory', 'Returned unused stock: 1 of Stapler (value: 8500.00)', NULL, 'Sun Jun 14 2026 11:10:08 GMT+0200 (Central Africa Time)'),
(65, 1, 'create_budget', 'budgets', 'Created budget: 2000000 for dept 4 FY 2026', NULL, 'Sun Jun 14 2026 11:10:43 GMT+0200 (Central Africa Time)'),
(66, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 11:16:42 GMT+0200 (Central Africa Time)'),
(67, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 11:26:42 GMT+0200 (Central Africa Time)'),
(68, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 11:33:24 GMT+0200 (Central Africa Time)'),
(69, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 11:50:09 GMT+0200 (Central Africa Time)'),
(70, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 11:55:10 GMT+0200 (Central Africa Time)'),
(71, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:02:47 GMT+0200 (Central Africa Time)'),
(72, 1, 'import_csv', 'inventory', 'Imported 4 items via CSV (inventory-import-template (1).csv): 4 inserted, 0 updated', NULL, 'Sun Jun 14 2026 12:05:39 GMT+0200 (Central Africa Time)'),
(73, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:08:21 GMT+0200 (Central Africa Time)'),
(74, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:08:50 GMT+0200 (Central Africa Time)'),
(75, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:09:57 GMT+0200 (Central Africa Time)'),
(76, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:15:17 GMT+0200 (Central Africa Time)'),
(77, 1, 'create', 'inventory', 'Created item: koko (SKU: INV-MQDN33U2-O9TE) @ 4570 RWF/unit', NULL, 'Sun Jun 14 2026 12:26:27 GMT+0200 (Central Africa Time)'),
(78, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:34:15 GMT+0200 (Central Africa Time)'),
(79, 1, 'delete', 'inventory', 'Soft-deleted item: koko (ID: 13)', NULL, 'Sun Jun 14 2026 12:36:33 GMT+0200 (Central Africa Time)'),
(80, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:41:37 GMT+0200 (Central Africa Time)'),
(81, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:48:14 GMT+0200 (Central Africa Time)'),
(82, 1, 'login', 'auth', 'User mugisha sting logged in', NULL, 'Sun Jun 14 2026 12:50:57 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: borrowings
-- --------------------------------------------
DROP TABLE IF EXISTS `borrowings`;
CREATE TABLE `borrowings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `borrower_name` varchar(200) NOT NULL,
  `borrower_phone` varchar(50) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_replacement_value` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_cost_at_time`) STORED,
  `borrow_date` date NOT NULL,
  `due_date` date NOT NULL,
  `status` enum('borrowed','returned','overdue','damaged','lost') NOT NULL DEFAULT 'borrowed',
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_status` (`status`),
  KEY `idx_due_date` (`due_date`),
  KEY `idx_borrower_name` (`borrower_name`),
  KEY `created_by` (`created_by`),
  KEY `idx_borrowings_borrower_name` (`borrower_name`(100)),
  KEY `idx_borrowings_item_id` (`item_id`),
  KEY `idx_borrowings_status` (`status`),
  KEY `idx_borrowings_borrow_date` (`borrow_date`),
  KEY `idx_borrowings_due_date` (`due_date`),
  KEY `idx_borrowings_created_at` (`created_at`),
  CONSTRAINT `borrowings_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `borrowings_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `borrowings` (`id`, `item_id`, `borrower_name`, `borrower_phone`, `quantity`, `unit_cost_at_time`, `total_replacement_value`, `borrow_date`, `due_date`, `status`, `created_by`, `created_at`, `updated_at`) VALUES
(1, 6, 'IROT', 'ORI', 8, '120000.00', '960000.00', 'Fri Jun 12 2026 00:00:00 GMT+0200 (Central Africa Time)', 'Sat Jun 13 2026 00:00:00 GMT+0200 (Central Africa Time)', 'returned', 1, 'Fri Jun 12 2026 21:25:41 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:26:16 GMT+0200 (Central Africa Time)'),
(2, 3, 'MUGISHA', '079574673', 3, '850000.00', '2550000.00', 'Fri Jun 12 2026 00:00:00 GMT+0200 (Central Africa Time)', 'Sat Jun 13 2026 00:00:00 GMT+0200 (Central Africa Time)', 'returned', 1, 'Fri Jun 12 2026 21:27:28 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:50:14 GMT+0200 (Central Africa Time)'),
(3, 4, 'FGHJ', '4567', 2, '650000.00', '1300000.00', 'Fri Jun 12 2026 00:00:00 GMT+0200 (Central Africa Time)', 'Sat Jun 13 2026 00:00:00 GMT+0200 (Central Africa Time)', 'returned', 1, 'Fri Jun 12 2026 21:30:06 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:50:02 GMT+0200 (Central Africa Time)'),
(4, 6, 'rue', 'zeze', 4, '120000.00', '480000.00', 'Fri Jun 12 2026 00:00:00 GMT+0200 (Central Africa Time)', 'Sat Jun 20 2026 00:00:00 GMT+0200 (Central Africa Time)', 'borrowed', 1, 'Fri Jun 12 2026 21:51:20 GMT+0200 (Central Africa Time)', NULL),
(5, 3, 'mugisha chris', '0987654321', 10, '850000.00', '8500000.00', 'Sun Jun 14 2026 00:00:00 GMT+0200 (Central Africa Time)', 'Fri Jun 19 2026 00:00:00 GMT+0200 (Central Africa Time)', 'borrowed', 1, 'Sun Jun 14 2026 09:14:37 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: budgets
-- --------------------------------------------
DROP TABLE IF EXISTS `budgets`;
CREATE TABLE `budgets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `department_id` int(11) NOT NULL,
  `fiscal_year` year(4) NOT NULL,
  `total_budget` decimal(14,2) NOT NULL DEFAULT 0.00,
  `description` varchar(255) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_department_fiscal` (`department_id`,`fiscal_year`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `budgets_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`),
  CONSTRAINT `budgets_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `budgets` (`id`, `department_id`, `fiscal_year`, `total_budget`, `description`, `created_by`, `created_at`, `updated_at`) VALUES
(1, 1, 2024, '50000000.00', 'General department annual budget', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(2, 2, 2024, '80000000.00', 'IT department annual budget', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(3, 3, 2024, '30000000.00', 'Logistics department annual budget', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(4, 4, 2024, '20000000.00', 'Finance department annual budget', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(5, 4, 2026, '2000000.00', NULL, 1, 'Sun Jun 14 2026 11:10:43 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: damage_liabilities
-- --------------------------------------------
DROP TABLE IF EXISTS `damage_liabilities`;
CREATE TABLE `damage_liabilities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liability_type` enum('damaged','lost') NOT NULL DEFAULT 'damaged',
  `borrowing_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `item_name` varchar(200) NOT NULL,
  `item_sku` varchar(50) NOT NULL,
  `borrower_name` varchar(200) NOT NULL,
  `borrower_id` int(11) DEFAULT NULL COMMENT 'FK to users table if borrower is a system user',
  `borrower_phone` varchar(50) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `paid_quantity` int(11) NOT NULL DEFAULT 0,
  `remaining_quantity` int(11) GENERATED ALWAYS AS (`quantity` - `paid_quantity`) STORED,
  `unit_cost` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `liability_percentage` decimal(5,2) NOT NULL DEFAULT 50.00,
  `replacement_cost` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Full replacement cost before liability percentage (qty * unit_cost)',
  `liability_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Actual amount borrower owes (replacement_cost * liability_percentage/100)',
  `amount_paid` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Total monetary amount paid so far',
  `balance` decimal(14,2) GENERATED ALWAYS AS (`liability_amount` - `amount_paid`) STORED COMMENT 'Remaining balance (liability_amount - amount_paid)',
  `status` enum('pending','unpaid','partially_paid','paid','waived') NOT NULL DEFAULT 'pending',
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_borrower_name` (`borrower_name`),
  KEY `idx_borrowing_id` (`borrowing_id`),
  KEY `item_id` (`item_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_liability_borrower` (`borrower_id`),
  KEY `idx_liability_amount` (`liability_amount`),
  KEY `idx_liability_balance` (`balance`),
  KEY `idx_liability_paid` (`amount_paid`),
  KEY `idx_damage_liabilities_borrowing_id` (`borrowing_id`),
  KEY `idx_damage_liabilities_item_name` (`item_name`(100)),
  KEY `idx_damage_liabilities_borrower_name` (`borrower_name`(100)),
  KEY `idx_damage_liabilities_type` (`liability_type`),
  KEY `idx_damage_liabilities_status` (`status`),
  KEY `idx_damage_liabilities_created_at` (`created_at`),
  KEY `idx_damage_liabilities_liability_amount` (`liability_amount`),
  KEY `idx_damage_liabilities_amount_paid` (`amount_paid`),
  CONSTRAINT `damage_liabilities_ibfk_1` FOREIGN KEY (`borrowing_id`) REFERENCES `borrowings` (`id`),
  CONSTRAINT `damage_liabilities_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `damage_liabilities_ibfk_3` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_liability_borrower` FOREIGN KEY (`borrower_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `damage_liabilities` (`id`, `liability_type`, `borrowing_id`, `item_id`, `item_name`, `item_sku`, `borrower_name`, `borrower_id`, `borrower_phone`, `quantity`, `paid_quantity`, `remaining_quantity`, `unit_cost`, `total_amount`, `liability_percentage`, `replacement_cost`, `liability_amount`, `amount_paid`, `balance`, `status`, `notes`, `created_by`, `paid_at`, `created_at`, `updated_at`) VALUES
(1, 'damaged', 1, 6, 'Filing Cabinet', 'INV-U7V8W-X9Y0', 'IROT', NULL, 'ORI', 1, 1, 0, '120000.00', '120000.00', '50.00', '120000.00', '120000.00', '60000.00', '60000.00', 'paid', NULL, 1, 'Fri Jun 12 2026 21:26:24 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:26:16 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:04:54 GMT+0200 (Central Africa Time)'),
(2, 'damaged', 2, 3, 'Laptop Dell Latitude', 'INV-F5G6H-I7J8', 'MUGISHA', NULL, '079574673', 1, 1, 0, '850000.00', '850000.00', '50.00', '850000.00', '850000.00', '425000.00', '425000.00', 'paid', NULL, 1, 'Fri Jun 12 2026 21:28:35 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:27:58 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:04:54 GMT+0200 (Central Africa Time)'),
(3, 'damaged', 2, 3, 'Laptop Dell Latitude', 'INV-F5G6H-I7J8', 'MUGISHA', NULL, '079574673', 1, 1, 0, '850000.00', '850000.00', '50.00', '850000.00', '850000.00', '850000.00', '0.00', 'paid', NULL, 1, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:30:36 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(4, 'damaged', 3, 4, 'Projector Epson', 'INV-K9L0M-N1O2', 'FGHJ', NULL, '4567', 1, 1, 0, '650000.00', '650000.00', '50.00', '650000.00', '650000.00', '650000.00', '0.00', 'paid', NULL, 1, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:30:50 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(5, 'damaged', 3, 4, 'Projector Epson', 'INV-K9L0M-N1O2', 'FGHJ', NULL, '4567', 1, 1, 0, '650000.00', '650000.00', '50.00', '650000.00', '650000.00', '650000.00', '0.00', 'paid', NULL, 1, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:50:02 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(6, 'damaged', 2, 3, 'Laptop Dell Latitude', 'INV-F5G6H-I7J8', 'MUGISHA', NULL, '079574673', 1, 1, 0, '850000.00', '850000.00', '50.00', '850000.00', '850000.00', '850000.00', '0.00', 'paid', NULL, 1, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:50:14 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(7, 'damaged', 4, 6, 'Filing Cabinet', 'INV-U7V8W-X9Y0', 'rue', NULL, 'zeze', 1, 1, 0, '120000.00', '120000.00', '50.00', '120000.00', '120000.00', '120000.00', '0.00', 'paid', NULL, 1, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 22:22:18 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(8, 'damaged', 4, 6, 'Filing Cabinet', 'INV-U7V8W-X9Y0', 'rue', NULL, 'zeze', 1, 1, 0, '120000.00', '120000.00', '50.00', '120000.00', '120000.00', '120000.00', '0.00', 'paid', NULL, 1, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 22:22:30 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(9, 'damaged', 5, 3, 'Laptop Dell Latitude', 'INV-F5G6H-I7J8', 'mugisha chris', NULL, '0987654321', 2, 2, 0, '850000.00', '850000.00', '50.00', '1700000.00', '850000.00', '850000.00', '0.00', 'paid', '[Damaged] OT', 1, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:15:23 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(10, 'lost', 5, 3, 'Laptop Dell Latitude', 'INV-F5G6H-I7J8', 'mugisha chris', NULL, '0987654321', 1, 1, 0, '850000.00', '850000.00', '100.00', '850000.00', '850000.00', '850000.00', '0.00', 'paid', '[Lost] MUGI', 1, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:15:44 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(11, 'damaged', 5, 3, 'Laptop Dell Latitude', 'INV-F5G6H-I7J8', 'mugisha chris', NULL, '0987654321', 1, 1, 0, '850000.00', '425000.00', '50.00', '850000.00', '425000.00', '425000.00', '0.00', 'paid', '[Damaged]', 1, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:46:48 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: damage_payments
-- --------------------------------------------
DROP TABLE IF EXISTS `damage_payments`;
CREATE TABLE `damage_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `liability_id` int(11) NOT NULL,
  `payment_quantity` int(11) NOT NULL,
  `unit_cost` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payment_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Actual payment amount',
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Explicit payment amount (not generated)',
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `paid_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_liability_id` (`liability_id`),
  KEY `idx_paid_at` (`paid_at`),
  KEY `created_by` (`created_by`),
  KEY `idx_damage_payments_liability_id` (`liability_id`),
  KEY `idx_damage_payments_paid_at` (`paid_at`),
  CONSTRAINT `damage_payments_ibfk_1` FOREIGN KEY (`liability_id`) REFERENCES `damage_liabilities` (`id`),
  CONSTRAINT `damage_payments_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `damage_payments` (`id`, `liability_id`, `payment_quantity`, `unit_cost`, `payment_amount`, `amount`, `notes`, `created_by`, `paid_at`, `created_at`) VALUES
(1, 1, 1, '120000.00', '60000.00', '60000.00', NULL, 1, 'Fri Jun 12 2026 21:26:24 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:26:24 GMT+0200 (Central Africa Time)'),
(2, 2, 1, '850000.00', '425000.00', '425000.00', NULL, 1, 'Fri Jun 12 2026 21:28:35 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:28:35 GMT+0200 (Central Africa Time)'),
(3, 11, 1, '425000.00', '0.00', '425000.00', NULL, 1, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(4, 10, 1, '850000.00', '0.00', '850000.00', NULL, 1, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(5, 9, 2, '425000.00', '0.00', '850000.00', NULL, 1, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(6, 8, 2, '60000.00', '0.00', '120000.00', NULL, 1, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(7, 7, 2, '60000.00', '0.00', '120000.00', NULL, 1, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(8, 6, 2, '425000.00', '0.00', '850000.00', NULL, 1, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(9, 5, 2, '325000.00', '0.00', '650000.00', NULL, 1, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(10, 4, 2, '325000.00', '0.00', '650000.00', NULL, 1, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(11, 3, 2, '425000.00', '0.00', '850000.00', NULL, 1, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: departments
-- --------------------------------------------
DROP TABLE IF EXISTS `departments`;
CREATE TABLE `departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `manager_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `departments` (`id`, `name`, `description`, `manager_id`, `created_at`, `updated_at`) VALUES
(1, 'General', 'General inventory department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(2, 'IT', 'Information Technology department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(3, 'Logistics', 'Logistics and transport department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(4, 'Finance', 'Finance and accounting department', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: items
-- --------------------------------------------
DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sku` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `unit` varchar(50) NOT NULL DEFAULT 'pcs',
  `quantity` int(11) NOT NULL DEFAULT 0,
  `minimum_stock` int(11) NOT NULL DEFAULT 0,
  `unit_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `selling_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` varchar(3) NOT NULL DEFAULT 'RWF',
  `item_type` enum('consumable','non-consumable') NOT NULL DEFAULT 'consumable',
  `department_id` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sku` (`sku`),
  KEY `idx_sku` (`sku`),
  KEY `idx_name` (`name`),
  KEY `idx_category` (`category`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_item_type` (`item_type`),
  KEY `idx_low_stock` (`quantity`,`minimum_stock`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `created_by` (`created_by`),
  KEY `idx_items_name` (`name`(100)),
  KEY `idx_items_sku` (`sku`),
  KEY `idx_items_department_id` (`department_id`),
  KEY `idx_items_category` (`category`),
  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `items_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `items` (`id`, `sku`, `name`, `description`, `category`, `unit`, `quantity`, `minimum_stock`, `unit_cost`, `selling_price`, `currency`, `item_type`, `department_id`, `created_by`, `image_url`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'INV-XZ3K9-M7XQ', 'Office Paper A4', 'Premium A4 copy paper, 500 sheets', 'Office Supplies', 'ream', 162, 20, '7720.69', '12000.00', 'RWF', 'consumable', 1, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 10:40:50 GMT+0200 (Central Africa Time)', NULL),
(2, 'INV-A1B2C-D3E4', 'Ballpoint Pens Blue', 'Blue ink ballpoint pens, box of 50', 'Office Supplies', 'box', 300, 50, '3500.00', '5000.00', 'RWF', 'consumable', 1, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL, NULL),
(3, 'INV-F5G6H-I7J8', 'Laptop Dell Latitude', 'Dell Latitude 3420, Core i5', 'Electronics', 'pcs', 5, 5, '850000.00', '1200000.00', 'RWF', 'non-consumable', 2, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 09:14:59 GMT+0200 (Central Africa Time)', NULL),
(4, 'INV-K9L0M-N1O2', 'Projector Epson', 'Epson EB-X51 LCD Projector', 'Electronics', 'pcs', 3, 2, '650000.00', '950000.00', 'RWF', 'non-consumable', 2, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:30:06 GMT+0200 (Central Africa Time)', NULL),
(5, 'INV-P3Q4R-S5T6', 'Printer Cartridge', 'HP LaserJet toner cartridge', 'Office Supplies', 'pcs', 25, 10, '45000.00', '65000.00', 'RWF', 'consumable', 1, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL, NULL),
(6, 'INV-U7V8W-X9Y0', 'Filing Cabinet', 'Metal filing cabinet, 4-drawer', 'Furniture', 'pcs', 3, 2, '120000.00', '180000.00', 'RWF', 'non-consumable', 1, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:51:20 GMT+0200 (Central Africa Time)', NULL),
(7, 'INV-Z1A2B-C3D4', 'Stapler', 'Heavy-duty stapler', 'Office Supplies', 'pcs', 38, 10, '8500.00', '12000.00', 'RWF', 'consumable', 1, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 11:10:08 GMT+0200 (Central Africa Time)', NULL),
(8, 'INV-E5F6G-H7I8', 'Notebook A5', 'A5 ruled notebook, pack of 5', 'Office Supplies', 'pack', 100, 20, '4500.00', '6500.00', 'RWF', 'consumable', 1, 1, NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL, NULL),
(9, 'LAP001', 'Dell Latitude Laptop', NULL, 'Electronics', 'pcs', 10, 2, '850000.00', '0.00', 'RWF', 'non-consumable', 4, 1, NULL, 'Sun Jun 14 2026 12:05:39 GMT+0200 (Central Africa Time)', NULL, NULL),
(10, 'CHR001', 'Office Chair', NULL, 'Furniture', 'pcs', 25, 5, '150000.00', '0.00', 'RWF', 'non-consumable', 1, 1, NULL, 'Sun Jun 14 2026 12:05:39 GMT+0200 (Central Africa Time)', NULL, NULL),
(11, 'PAP001', 'Office Paper A4', NULL, 'Office Supplies', 'ream', 100, 20, '12000.00', '0.00', 'RWF', 'consumable', 4, 1, NULL, 'Sun Jun 14 2026 12:05:39 GMT+0200 (Central Africa Time)', NULL, NULL),
(12, 'PEN001', 'Ballpoint Pens Blue', NULL, 'Office Supplies', 'box', 200, 10, '5000.00', '0.00', 'RWF', 'consumable', 4, 1, NULL, 'Sun Jun 14 2026 12:05:39 GMT+0200 (Central Africa Time)', NULL, NULL),
(13, 'INV-MQDN33U2-O9TE', 'koko', '', 'Electronics', 'pcs', 123, 5, '4570.00', '5400.00', 'RWF', 'non-consumable', 4, 1, '/uploads/item-1781432787180-898005713.JPG', 'Sun Jun 14 2026 12:26:27 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 12:36:33 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 12:36:33 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: leftovers
-- --------------------------------------------
DROP TABLE IF EXISTS `leftovers`;
CREATE TABLE `leftovers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_out_id` int(11) NOT NULL,
  `returned_quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_value` decimal(14,2) GENERATED ALWAYS AS (`returned_quantity` * `unit_cost_at_time`) STORED,
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_stock_out_id` (`stock_out_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_leftovers_stock_out_id` (`stock_out_id`),
  KEY `idx_leftovers_created_at` (`created_at`),
  CONSTRAINT `leftovers_ibfk_1` FOREIGN KEY (`stock_out_id`) REFERENCES `stock_out` (`id`),
  CONSTRAINT `leftovers_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `leftovers` (`id`, `stock_out_id`, `returned_quantity`, `unit_cost_at_time`, `total_value`, `notes`, `created_by`, `created_at`) VALUES
(1, 1, 2, '8500.00', '17000.00', NULL, 1, 'Sun Jun 14 2026 11:09:35 GMT+0200 (Central Africa Time)'),
(2, 1, 1, '8500.00', '8500.00', NULL, 1, 'Sun Jun 14 2026 11:10:08 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: notifications
-- --------------------------------------------
DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `module` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_read_user` (`is_read`,`user_id`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `notifications` (`id`, `user_id`, `title`, `message`, `module`, `reference_id`, `is_read`, `created_at`) VALUES
(1, 1, 'Damage Reported', '1 of Filing Cabinet by IROT reported as damaged. Total liability: 120000.00', 'damage_liabilities', 1, 0, 'Fri Jun 12 2026 21:26:16 GMT+0200 (Central Africa Time)'),
(2, 1, 'Damage Reported', '1 of Laptop Dell Latitude by MUGISHA reported as damaged. Total liability: 850000.00', 'damage_liabilities', 2, 0, 'Fri Jun 12 2026 21:27:58 GMT+0200 (Central Africa Time)'),
(3, 1, 'Damage Reported', '1 of Laptop Dell Latitude by MUGISHA reported as damaged. Total liability: 850000.00', 'damage_liabilities', 3, 0, 'Fri Jun 12 2026 21:30:36 GMT+0200 (Central Africa Time)'),
(4, 1, 'Damage Reported', '1 of Projector Epson by FGHJ reported as damaged. Total liability: 650000.00', 'damage_liabilities', 4, 0, 'Fri Jun 12 2026 21:30:50 GMT+0200 (Central Africa Time)'),
(5, 1, 'Damage Reported', '1 of Projector Epson by FGHJ reported as damaged. Total liability: 650000.00', 'damage_liabilities', 5, 0, 'Fri Jun 12 2026 21:50:02 GMT+0200 (Central Africa Time)'),
(6, 1, 'Damage Reported', '1 of Laptop Dell Latitude by MUGISHA reported as damaged. Total liability: 850000.00', 'damage_liabilities', 6, 0, 'Fri Jun 12 2026 21:50:14 GMT+0200 (Central Africa Time)'),
(7, 1, 'Damage Reported', '1 of Filing Cabinet by rue reported as damaged. Total liability: 120000.00', 'damage_liabilities', 7, 0, 'Fri Jun 12 2026 22:22:18 GMT+0200 (Central Africa Time)'),
(8, 1, 'Damage Reported', '1 of Filing Cabinet by rue reported as damaged. Total liability: 120000.00', 'damage_liabilities', 8, 0, 'Fri Jun 12 2026 22:22:30 GMT+0200 (Central Africa Time)'),
(9, 1, 'Damage Reported', '2 of Laptop Dell Latitude by mugisha chris reported as damaged. Total liability: 850000.00. Status: Pending', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:15:23 GMT+0200 (Central Africa Time)'),
(10, 2, 'Damage Reported', '2 of Laptop Dell Latitude by mugisha chris reported as damaged. Total liability: 850000.00. Status: Pending', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:15:23 GMT+0200 (Central Africa Time)'),
(11, 3, 'Damage Reported', '2 of Laptop Dell Latitude by mugisha chris reported as damaged. Total liability: 850000.00. Status: Pending', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:15:23 GMT+0200 (Central Africa Time)'),
(12, 1, 'Lost Item Reported', '1 of Laptop Dell Latitude by mugisha chris reported as lost. Total liability: 850000.00. Status: Pending', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:15:44 GMT+0200 (Central Africa Time)'),
(13, 2, 'Lost Item Reported', '1 of Laptop Dell Latitude by mugisha chris reported as lost. Total liability: 850000.00. Status: Pending', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:15:44 GMT+0200 (Central Africa Time)'),
(14, 3, 'Lost Item Reported', '1 of Laptop Dell Latitude by mugisha chris reported as lost. Total liability: 850000.00. Status: Pending', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:15:44 GMT+0200 (Central Africa Time)'),
(15, 1, 'Damage Reported', '1 of Laptop Dell Latitude by mugisha chris reported as damaged. Total liability: 425000.00. Status: Pending', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:46:48 GMT+0200 (Central Africa Time)'),
(16, 2, 'Damage Reported', '1 of Laptop Dell Latitude by mugisha chris reported as damaged. Total liability: 425000.00. Status: Pending', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:46:48 GMT+0200 (Central Africa Time)'),
(17, 3, 'Damage Reported', '1 of Laptop Dell Latitude by mugisha chris reported as damaged. Total liability: 425000.00. Status: Pending', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:46:48 GMT+0200 (Central Africa Time)'),
(18, 1, 'Liability Payment Recorded', 'Payment of 425000.00 recorded for damage liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(19, 2, 'Liability Payment Recorded', 'Payment of 425000.00 recorded for damage liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(20, 3, 'Liability Payment Recorded', 'Payment of 425000.00 recorded for damage liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(21, 1, 'Liability Paid', 'Damage liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 425000.00.', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(22, 2, 'Liability Paid', 'Damage liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 425000.00.', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(23, 3, 'Liability Paid', 'Damage liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 425000.00.', 'damage_liabilities', 11, 0, 'Sun Jun 14 2026 09:56:11 GMT+0200 (Central Africa Time)'),
(24, 1, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for loss liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(25, 2, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for loss liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(26, 3, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for loss liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(27, 1, 'Liability Paid', 'Loss liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(28, 2, 'Liability Paid', 'Loss liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(29, 3, 'Liability Paid', 'Loss liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 10, 0, 'Sun Jun 14 2026 09:56:40 GMT+0200 (Central Africa Time)'),
(30, 1, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(31, 2, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(32, 3, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - mugisha chris (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(33, 1, 'Liability Paid', 'Damage liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(34, 2, 'Liability Paid', 'Damage liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(35, 3, 'Liability Paid', 'Damage liability for mugisha chris (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 9, 0, 'Sun Jun 14 2026 09:56:43 GMT+0200 (Central Africa Time)'),
(36, 1, 'Liability Payment Recorded', 'Payment of 120000.00 recorded for damage liability - rue (Filing Cabinet). Status: paid.', 'damage_liabilities', 8, 0, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(37, 2, 'Liability Payment Recorded', 'Payment of 120000.00 recorded for damage liability - rue (Filing Cabinet). Status: paid.', 'damage_liabilities', 8, 0, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(38, 3, 'Liability Payment Recorded', 'Payment of 120000.00 recorded for damage liability - rue (Filing Cabinet). Status: paid.', 'damage_liabilities', 8, 0, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(39, 1, 'Liability Paid', 'Damage liability for rue (Filing Cabinet) has been fully paid. Total paid: 120000.00.', 'damage_liabilities', 8, 0, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(40, 2, 'Liability Paid', 'Damage liability for rue (Filing Cabinet) has been fully paid. Total paid: 120000.00.', 'damage_liabilities', 8, 0, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(41, 3, 'Liability Paid', 'Damage liability for rue (Filing Cabinet) has been fully paid. Total paid: 120000.00.', 'damage_liabilities', 8, 0, 'Sun Jun 14 2026 09:56:48 GMT+0200 (Central Africa Time)'),
(42, 1, 'Liability Payment Recorded', 'Payment of 120000.00 recorded for damage liability - rue (Filing Cabinet). Status: paid.', 'damage_liabilities', 7, 0, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(43, 2, 'Liability Payment Recorded', 'Payment of 120000.00 recorded for damage liability - rue (Filing Cabinet). Status: paid.', 'damage_liabilities', 7, 0, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(44, 3, 'Liability Payment Recorded', 'Payment of 120000.00 recorded for damage liability - rue (Filing Cabinet). Status: paid.', 'damage_liabilities', 7, 0, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(45, 1, 'Liability Paid', 'Damage liability for rue (Filing Cabinet) has been fully paid. Total paid: 120000.00.', 'damage_liabilities', 7, 0, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(46, 2, 'Liability Paid', 'Damage liability for rue (Filing Cabinet) has been fully paid. Total paid: 120000.00.', 'damage_liabilities', 7, 0, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(47, 3, 'Liability Paid', 'Damage liability for rue (Filing Cabinet) has been fully paid. Total paid: 120000.00.', 'damage_liabilities', 7, 0, 'Sun Jun 14 2026 09:56:51 GMT+0200 (Central Africa Time)'),
(48, 1, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - MUGISHA (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 6, 0, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(49, 2, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - MUGISHA (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 6, 0, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(50, 3, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - MUGISHA (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 6, 0, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)');
INSERT INTO `notifications` (`id`, `user_id`, `title`, `message`, `module`, `reference_id`, `is_read`, `created_at`) VALUES
(51, 1, 'Liability Paid', 'Damage liability for MUGISHA (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 6, 0, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(52, 2, 'Liability Paid', 'Damage liability for MUGISHA (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 6, 0, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(53, 3, 'Liability Paid', 'Damage liability for MUGISHA (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 6, 0, 'Sun Jun 14 2026 09:56:55 GMT+0200 (Central Africa Time)'),
(54, 1, 'Liability Payment Recorded', 'Payment of 650000.00 recorded for damage liability - FGHJ (Projector Epson). Status: paid.', 'damage_liabilities', 5, 0, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(55, 2, 'Liability Payment Recorded', 'Payment of 650000.00 recorded for damage liability - FGHJ (Projector Epson). Status: paid.', 'damage_liabilities', 5, 0, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(56, 3, 'Liability Payment Recorded', 'Payment of 650000.00 recorded for damage liability - FGHJ (Projector Epson). Status: paid.', 'damage_liabilities', 5, 0, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(57, 1, 'Liability Paid', 'Damage liability for FGHJ (Projector Epson) has been fully paid. Total paid: 650000.00.', 'damage_liabilities', 5, 0, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(58, 2, 'Liability Paid', 'Damage liability for FGHJ (Projector Epson) has been fully paid. Total paid: 650000.00.', 'damage_liabilities', 5, 0, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(59, 3, 'Liability Paid', 'Damage liability for FGHJ (Projector Epson) has been fully paid. Total paid: 650000.00.', 'damage_liabilities', 5, 0, 'Sun Jun 14 2026 09:56:58 GMT+0200 (Central Africa Time)'),
(60, 1, 'Liability Payment Recorded', 'Payment of 650000.00 recorded for damage liability - FGHJ (Projector Epson). Status: paid.', 'damage_liabilities', 4, 0, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(61, 2, 'Liability Payment Recorded', 'Payment of 650000.00 recorded for damage liability - FGHJ (Projector Epson). Status: paid.', 'damage_liabilities', 4, 0, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(62, 3, 'Liability Payment Recorded', 'Payment of 650000.00 recorded for damage liability - FGHJ (Projector Epson). Status: paid.', 'damage_liabilities', 4, 0, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(63, 1, 'Liability Paid', 'Damage liability for FGHJ (Projector Epson) has been fully paid. Total paid: 650000.00.', 'damage_liabilities', 4, 0, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(64, 2, 'Liability Paid', 'Damage liability for FGHJ (Projector Epson) has been fully paid. Total paid: 650000.00.', 'damage_liabilities', 4, 0, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(65, 3, 'Liability Paid', 'Damage liability for FGHJ (Projector Epson) has been fully paid. Total paid: 650000.00.', 'damage_liabilities', 4, 0, 'Sun Jun 14 2026 09:57:01 GMT+0200 (Central Africa Time)'),
(66, 1, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - MUGISHA (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 3, 0, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(67, 2, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - MUGISHA (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 3, 0, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(68, 3, 'Liability Payment Recorded', 'Payment of 850000.00 recorded for damage liability - MUGISHA (Laptop Dell Latitude). Status: paid.', 'damage_liabilities', 3, 0, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(69, 1, 'Liability Paid', 'Damage liability for MUGISHA (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 3, 0, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(70, 2, 'Liability Paid', 'Damage liability for MUGISHA (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 3, 0, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(71, 3, 'Liability Paid', 'Damage liability for MUGISHA (Laptop Dell Latitude) has been fully paid. Total paid: 850000.00.', 'damage_liabilities', 3, 0, 'Sun Jun 14 2026 09:57:03 GMT+0200 (Central Africa Time)'),
(72, 1, 'Low Stock Alert', 'Item "koko" (SKU: INV-MQDN33U2-O9TE) has low stock. Current quantity: 123, Minimum: 5.', 'inventory', NULL, 0, 'Sun Jun 14 2026 12:26:27 GMT+0200 (Central Africa Time)'),
(73, 2, 'Low Stock Alert', 'Item "koko" (SKU: INV-MQDN33U2-O9TE) has low stock. Current quantity: 123, Minimum: 5.', 'inventory', NULL, 0, 'Sun Jun 14 2026 12:26:27 GMT+0200 (Central Africa Time)'),
(74, 3, 'Low Stock Alert', 'Item "koko" (SKU: INV-MQDN33U2-O9TE) has low stock. Current quantity: 123, Minimum: 5.', 'inventory', NULL, 0, 'Sun Jun 14 2026 12:26:27 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: requests
-- --------------------------------------------
DROP TABLE IF EXISTS `requests`;
CREATE TABLE `requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `requester_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `allocated_quantity` int(11) DEFAULT NULL,
  `justification` text DEFAULT NULL,
  `status` enum('pending','approved','rejected','allocated') DEFAULT 'pending',
  `reviewed_by` int(11) DEFAULT NULL,
  `reviewed_notes` text DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_requester_id` (`requester_id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `reviewed_by` (`reviewed_by`),
  KEY `idx_requests_requester_id` (`requester_id`),
  KEY `idx_requests_item_id` (`item_id`),
  KEY `idx_requests_status` (`status`),
  KEY `idx_requests_created_at` (`created_at`),
  CONSTRAINT `requests_ibfk_1` FOREIGN KEY (`requester_id`) REFERENCES `users` (`id`),
  CONSTRAINT `requests_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `requests_ibfk_3` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: returns
-- --------------------------------------------
DROP TABLE IF EXISTS `returns`;
CREATE TABLE `returns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `borrowing_id` int(11) NOT NULL,
  `returned_quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_value` decimal(14,2) GENERATED ALWAYS AS (`returned_quantity` * `unit_cost_at_time`) STORED,
  `item_condition` enum('good','damaged','lost') DEFAULT 'good',
  `notes` text DEFAULT NULL,
  `return_date` date NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_borrowing_id` (`borrowing_id`),
  KEY `idx_item_condition` (`item_condition`),
  KEY `idx_return_date` (`return_date`),
  KEY `created_by` (`created_by`),
  KEY `idx_returns_borrowing_id` (`borrowing_id`),
  KEY `idx_returns_return_date` (`return_date`),
  KEY `idx_returns_condition` (`item_condition`),
  KEY `idx_returns_created_at` (`created_at`),
  CONSTRAINT `returns_ibfk_1` FOREIGN KEY (`borrowing_id`) REFERENCES `borrowings` (`id`),
  CONSTRAINT `returns_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `returns` (`id`, `borrowing_id`, `returned_quantity`, `unit_cost_at_time`, `total_value`, `item_condition`, `notes`, `return_date`, `created_by`, `created_at`) VALUES
(1, 1, 7, '120000.00', '840000.00', 'good', NULL, 'Fri Jun 12 2026 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:25:58 GMT+0200 (Central Africa Time)'),
(2, 5, 3, '850000.00', '2550000.00', 'good', NULL, 'Sun Jun 14 2026 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Sun Jun 14 2026 09:14:59 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: roles
-- --------------------------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `roles` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES
(1, 'super_admin', 'System owner with unrestricted access', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(2, 'admin', 'Operations manager with full inventory access', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(3, 'stock_manager', 'Warehouse/storekeeper managing daily operations', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(4, 'staff', 'Department employee requesting supplies', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL);

-- --------------------------------------------
-- Table: stock_adjustments
-- --------------------------------------------
DROP TABLE IF EXISTS `stock_adjustments`;
CREATE TABLE `stock_adjustments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `adjustment_type` enum('increase','decrease') NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_cost_at_time`) STORED,
  `reason` varchar(255) NOT NULL,
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_adjustment_type` (`adjustment_type`),
  KEY `idx_reason` (`reason`),
  KEY `created_by` (`created_by`),
  KEY `idx_stock_adjustments_date` (`created_at`),
  KEY `idx_stock_adjustments_item_id` (`item_id`),
  KEY `idx_stock_adjustments_type` (`adjustment_type`),
  CONSTRAINT `stock_adjustments_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `stock_adjustments_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: stock_in
-- --------------------------------------------
DROP TABLE IF EXISTS `stock_in`;
CREATE TABLE `stock_in` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_price`) STORED,
  `supplier` varchar(200) DEFAULT NULL,
  `supplier_type` varchar(50) DEFAULT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `department_id` int(11) DEFAULT NULL,
  `date` date NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_date` (`date`),
  KEY `idx_supplier` (`supplier`),
  KEY `created_by` (`created_by`),
  KEY `idx_stock_in_date` (`date`),
  KEY `idx_stock_in_item_id` (`item_id`),
  KEY `idx_stock_in_supplier` (`supplier`(100)),
  KEY `idx_stock_in_supplier_type` (`supplier_type`),
  KEY `idx_stock_in_reference` (`reference_number`),
  KEY `idx_stock_in_created_at` (`created_at`),
  KEY `idx_stock_in_department_id` (`department_id`),
  CONSTRAINT `stock_in_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `stock_in_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `stock_in` (`id`, `item_id`, `quantity`, `unit_price`, `total_cost`, `supplier`, `supplier_type`, `reference_number`, `notes`, `department_id`, `date`, `created_by`, `created_at`) VALUES
(1, 1, 100, '8000.00', '800000.00', 'Office Depot Rwanda', 'Wholesale', 'PO-2024-001', 'Initial stock', NULL, 'Mon Jan 15 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(2, 2, 200, '3200.00', '640000.00', 'Office Depot Rwanda', 'Wholesale', 'PO-2024-002', 'Initial stock', NULL, 'Mon Jan 15 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(3, 3, 10, '800000.00', '8000000.00', 'Dell East Africa', 'Manufacturer', 'PO-2024-003', 'Initial stock', NULL, 'Sat Jan 20 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(4, 4, 5, '620000.00', '3100000.00', 'Epson Rwanda', 'Manufacturer', 'PO-2024-004', 'Initial stock', NULL, 'Sat Jan 20 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(5, 1, 50, '8500.00', '425000.00', 'Stationery World', 'Retail', 'PO-2024-010', 'Restock', NULL, 'Thu Feb 01 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(6, 5, 25, '42000.00', '1050000.00', 'HP Rwanda', 'Manufacturer', 'PO-2024-011', 'Initial stock', NULL, 'Mon Feb 05 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(7, 6, 8, '110000.00', '880000.00', 'Furniture Mart', 'Wholesale', 'PO-2024-012', 'Initial stock', NULL, 'Sat Feb 10 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(8, 7, 50, '8000.00', '400000.00', 'Office Depot Rwanda', 'Wholesale', 'PO-2024-013', 'Initial stock', NULL, 'Thu Feb 15 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(9, 8, 100, '4200.00', '420000.00', 'Stationery World', 'Retail', 'PO-2024-014', 'Initial stock', NULL, 'Tue Feb 20 2024 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(10, 1, 12, '2146.00', '25752.00', 'ERT', 'Donated', '223345', 'ZEDGFGH', 2, 'Sun Jun 14 2026 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Sun Jun 14 2026 10:40:50 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: stock_out
-- --------------------------------------------
DROP TABLE IF EXISTS `stock_out`;
CREATE TABLE `stock_out` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_cost_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `selling_price_at_time` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(14,2) GENERATED ALWAYS AS (`quantity` * `unit_cost_at_time`) STORED,
  `gross_margin` decimal(12,2) GENERATED ALWAYS AS (`selling_price_at_time` - `unit_cost_at_time`) STORED,
  `gross_margin_pct` decimal(5,2) GENERATED ALWAYS AS (case when `selling_price_at_time` > 0 then round((`selling_price_at_time` - `unit_cost_at_time`) / `selling_price_at_time` * 100,2) else 0 end) STORED,
  `recipient` varchar(200) NOT NULL,
  `department` varchar(100) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `date` date NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_date` (`date`),
  KEY `idx_recipient` (`recipient`),
  KEY `created_by` (`created_by`),
  KEY `idx_stock_out_date` (`date`),
  KEY `idx_stock_out_item_id` (`item_id`),
  KEY `idx_stock_out_recipient` (`recipient`(100)),
  KEY `idx_stock_out_department` (`department`),
  KEY `idx_stock_out_created_at` (`created_at`),
  CONSTRAINT `stock_out_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `stock_out_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `stock_out` (`id`, `item_id`, `quantity`, `unit_cost_at_time`, `selling_price_at_time`, `total_cost`, `gross_margin`, `gross_margin_pct`, `recipient`, `department`, `reason`, `date`, `created_by`, `created_at`) VALUES
(1, 7, 5, '8500.00', '12000.00', '42500.00', '3500.00', '29.17', 'loypr', NULL, 'pzoe', 'Sun Jun 14 2026 00:00:00 GMT+0200 (Central Africa Time)', 1, 'Sun Jun 14 2026 11:05:22 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: super_admin_audit_log
-- --------------------------------------------
DROP TABLE IF EXISTS `super_admin_audit_log`;
CREATE TABLE `super_admin_audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `actor_id` int(11) NOT NULL,
  `action` varchar(100) NOT NULL,
  `target_user_id` int(11) DEFAULT NULL,
  `details` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `status` enum('blocked','allowed') DEFAULT 'blocked',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_actor_id` (`actor_id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------
-- Table: user_departments
-- --------------------------------------------
DROP TABLE IF EXISTS `user_departments`;
CREATE TABLE `user_departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `department_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_department` (`user_id`,`department_id`),
  KEY `department_id` (`department_id`),
  CONSTRAINT `user_departments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_departments_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `user_departments` (`id`, `user_id`, `department_id`, `created_at`) VALUES
(1, 2, 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(2, 2, 2, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(3, 3, 1, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)'),
(4, 3, 3, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)');

-- --------------------------------------------
-- Table: users
-- --------------------------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role_id` int(11) NOT NULL,
  `department_id` int(11) DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `last_login` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_email` (`email`),
  KEY `idx_role_id` (`role_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
  CONSTRAINT `users_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`id`, `full_name`, `email`, `password`, `role_id`, `department_id`, `status`, `last_login`, `created_at`, `updated_at`) VALUES
(1, 'mugisha sting', 'admin@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 1, NULL, 'active', 'Sun Jun 14 2026 12:50:57 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 12:50:57 GMT+0200 (Central Africa Time)'),
(2, 'John Manager', 'john@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 2, 1, 'active', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL),
(3, 'Stock Keeper', 'stock@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 3, 1, 'active', 'Sun Jun 14 2026 10:50:24 GMT+0200 (Central Africa Time)', 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', 'Sun Jun 14 2026 10:50:24 GMT+0200 (Central Africa Time)'),
(4, 'Staff User', 'staff@mizero.com', '$2a$12$Q1PV.rRib.a5X.3u2HqOkOyB12B1LJttosa3Z.W0LBMqt.dN.dAM6', 4, NULL, 'active', NULL, 'Fri Jun 12 2026 21:16:24 GMT+0200 (Central Africa Time)', NULL);

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- Backup complete
-- ============================================
