const { getApp, loginAs, authRequest, getCsrfOnly } = require('./helpers');
const request = require('supertest');

let app;
let auth;
let csrf;

beforeAll(async () => {
  app = getApp();
  auth = await loginAs('admin@mizero.com', 'password123');
  csrf = await getCsrfOnly();
});

describe('📄 CSV Import - Preview', () => {
  test('should reject without file', async () => {
    const res = await authRequest('post', '/api/items/import/csv/preview', auth);
    expect(res.status).toBe(400);
    expect(res.body.message).toMatch(/CSV file/i);
  });

  test('should reject invalid CSV data', async () => {
    const res = await authRequest('post', '/api/items/import/csv/preview', auth)
      .attach('file', Buffer.from('not,valid,csv\na,b'), 'test.csv');

    // Should still try to parse - it's valid CSV but will fail validation
    expect(res.status).toBe(200);
    expect(res.body).toHaveProperty('validCount');
    expect(res.body).toHaveProperty('invalidCount');
  });

  test('should return validation results for empty data', async () => {
    const csvContent = 'name,category,unit,quantity,minimum_stock,item_type,department,unit_cost,currency\n';
    const res = await authRequest('post', '/api/items/import/csv/preview', auth)
      .attach('file', Buffer.from(csvContent), 'empty.csv');

    expect(res.status).toBe(400);
    expect(res.body.message).toMatch(/empty/i);
  });

  test('should accept valid CSV preview', async () => {
    // Fetch a department name from the DB for a valid preview
    const deptRes = await authRequest('get', '/api/departments', auth);
    const deptName = deptRes.body[0]?.name || 'General Store';

    const csvContent = [
      'name,category,unit,quantity,minimum_stock,item_type,department,unit_cost,currency',
      `Test Item A,Electronics,pcs,10,2,consumable,${deptName},5000,RWF`,
      `Test Item B,Furniture,pcs,5,1,non-consumable,${deptName},25000,RWF`
    ].join('\n');

    const res = await authRequest('post', '/api/items/import/csv/preview', auth)
      .attach('file', Buffer.from(csvContent), 'test-preview.csv');

    expect(res.status).toBe(200);
    expect(res.body.totalRows).toBe(2);
    expect(res.body.validCount).toBe(2);
    expect(res.body.invalidCount).toBe(0);
    expect(res.body.columns).toEqual(expect.arrayContaining(['name', 'category', 'unit', 'quantity', 'minimum_stock', 'item_type', 'department', 'unit_cost', 'currency']));
    expect(res.body.skuAutoGenerated).toBe(true);
  });
});

describe('📄 CSV Import - Execute', () => {
  test('should reject without file', async () => {
    const res = await authRequest('post', '/api/items/import/csv', auth);
    expect(res.status).toBe(400);
    expect(res.body.message).toMatch(/CSV file/i);
  });

  test('should import valid CSV data with auto-generated SKUs', async () => {
    const deptRes = await authRequest('get', '/api/departments', auth);
    const deptName = deptRes.body[0]?.name || 'General Store';

    const csvContent = [
      'name,category,unit,quantity,minimum_stock,item_type,department,unit_cost,currency',
      `CSV Import Test A,Test,pcs,20,5,consumable,${deptName},3000,RWF`,
      `CSV Import Test B,Test,pcs,15,3,non-consumable,${deptName},12000,RWF`
    ].join('\n');

    const res = await authRequest('post', '/api/items/import/csv', auth)
      .attach('file', Buffer.from(csvContent), 'test-import.csv');

    expect(res.status).toBe(200);
    expect(res.body.totalRows).toBe(2);
    expect(res.body.inserted).toBe(2);
    expect(res.body.message).toMatch(/Import complete/i);
  });

  test('should merge quantity into existing matching items', async () => {
    const deptRes = await authRequest('get', '/api/departments', auth);
    const deptName = deptRes.body[0]?.name || 'General Store';

    // First import creates items
    const csvContent = [
      'name,category,unit,quantity,minimum_stock,item_type,department,unit_cost,currency',
      `Merge Test Item,Test,pcs,10,2,consumable,${deptName},5000,RWF`
    ].join('\n');

    const res1 = await authRequest('post', '/api/items/import/csv', auth)
      .attach('file', Buffer.from(csvContent), 'merge-first.csv');
    expect(res1.status).toBe(200);
    expect(res1.body.inserted).toBe(1);
    expect(res1.body.merged).toBe(0);

    // Second import with same name+category+dept+type should MERGE, not insert
    const res2 = await authRequest('post', '/api/items/import/csv', auth)
      .attach('file', Buffer.from(csvContent), 'merge-second.csv');
    expect(res2.status).toBe(200);
    expect(res2.body.inserted).toBe(0);
    expect(res2.body.merged).toBe(1);
  });

  test('should restore soft-deleted items on re-import', async () => {
    const deptRes = await authRequest('get', '/api/departments', auth);
    const deptName = deptRes.body[0]?.name || 'General Store';

    // First import creates an item
    const csvContent = [
      'name,category,unit,quantity,minimum_stock,item_type,department,unit_cost,currency',
      `Restore Test Item,Test,pcs,15,3,consumable,${deptName},8000,RWF`
    ].join('\n');

    const res1 = await authRequest('post', '/api/items/import/csv', auth)
      .attach('file', Buffer.from(csvContent), 'restore-first.csv');
    expect(res1.status).toBe(200);
    expect(res1.body.inserted).toBe(1);

    // Find the item ID to soft-delete it
    const listRes = await authRequest('get', '/api/items', auth);
    const item = listRes.body.items.find(i => i.name === 'Restore Test Item');
    expect(item).toBeTruthy();

    // Soft-delete the item
    await authRequest('delete', `/api/items/${item.id}`, auth);

    // Re-import the same item — should restore, not create new
    const res2 = await authRequest('post', '/api/items/import/csv', auth)
      .attach('file', Buffer.from(csvContent), 'restore-second.csv');
    expect(res2.status).toBe(200);
    expect(res2.body.restored).toBe(1);
    expect(res2.body.inserted).toBe(0);
  });
});

describe('📄 CSV Export', () => {
  test('should export CSV template', async () => {
    const res = await authRequest('get', '/api/items/export/csv/template', auth);
    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toMatch(/csv/);
    expect(res.headers['content-disposition']).toMatch(/template/);
    expect(res.text).toBeTruthy();
  });

  test('should export inventory CSV', async () => {
    const res = await authRequest('get', '/api/items/export/csv', auth);
    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toMatch(/csv/);
  });
});
