/**
 * CSV Input Sanitization Utility
 *
 * Sanitizes raw CSV data to prevent injection attacks and normalize data.
 * Applied to every row during CSV import.
 */

// Control characters that should be stripped from string fields
const CONTROL_CHARS = /[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g;

/**
 * Strip leading/trailing whitespace and control characters from a string value.
 * Returns null for empty/null/undefined inputs.
 */
function sanitizeString(value) {
  if (value === null || value === undefined) return null;
  if (typeof value === 'string') {
    // Remove control characters, then trim
    const cleaned = value.replace(CONTROL_CHARS, '').trim();
    return cleaned || null;
  }
  return String(value).replace(CONTROL_CHARS, '').trim() || null;
}

/**
 * Sanitize a numeric string value.
 * Returns the parsed number, or 0 if invalid.
 */
function sanitizeNumeric(value) {
  if (value === null || value === undefined) return 0;
  const cleaned = String(value).replace(CONTROL_CHARS, '').trim();
  const parsed = parseFloat(cleaned);
  return isNaN(parsed) ? 0 : parsed;
}

/**
 * Sanitize an integer value.
 * Returns the parsed integer, or 0 if invalid.
 */
function sanitizeInteger(value) {
  if (value === null || value === undefined) return 0;
  const cleaned = String(value).replace(CONTROL_CHARS, '').trim();
  const parsed = parseInt(cleaned, 10);
  return isNaN(parsed) ? 0 : parsed;
}

/**
 * Sanitize a whole CSV row — trim all fields, clean control characters,
 * and convert types to their expected formats.
 *
 * @param {Object} row - Raw CSV row object
 * @returns {Object} Sanitized row with cleaned values
 */
function sanitizeCsvRow(row) {
  if (!row || typeof row !== 'object') return {};

  const sanitized = {};

  // String fields — trim and clean
  // NOTE: sku is NOT imported from CSV — it is auto-generated by the system.
  sanitized.name = sanitizeString(row.name);
  sanitized.category = sanitizeString(row.category);
  sanitized.unit = sanitizeString(row.unit) || 'pcs';
  sanitized.item_type = sanitizeString(row.item_type);
  sanitized.currency = sanitizeString(row.currency);
  sanitized.department = sanitizeString(row.department);

  // Numeric fields — parse to proper types
  sanitized.quantity = sanitizeInteger(row.quantity);
  sanitized.minimum_stock = sanitizeInteger(row.minimum_stock);
  sanitized.unit_cost = sanitizeNumeric(row.unit_cost);

  return sanitized;
}

/**
 * Validate that a sanitized row has the required fields.
 * Returns an array of error messages (empty = valid).
 */
function validateSanitizedRow(sanitized) {
  const errors = [];

  // SKU is auto-generated by the system — not required in CSV
  if (!sanitized.name) errors.push('Item name is required');
  if (!sanitized.department) errors.push('Department is required');
  if (!sanitized.currency) errors.push('Currency is required');
  if (!sanitized.item_type) errors.push('Item type is required');

  if (sanitized.quantity < 0) errors.push('Quantity cannot be negative');
  if (sanitized.minimum_stock < 0) errors.push('Minimum stock cannot be negative');
  if (sanitized.unit_cost < 0) errors.push('Unit cost cannot be negative');

  if (!['consumable', 'non-consumable'].includes(sanitized.item_type)) {
    errors.push('Item type must be "consumable" or "non-consumable"');
  }

  if (!['RWF', 'USD', 'EUR'].includes(sanitized.currency)) {
    errors.push('Currency must be one of: RWF, USD, EUR');
  }

  return errors;
}

module.exports = { sanitizeCsvRow, validateSanitizedRow, sanitizeString, sanitizeNumeric, sanitizeInteger };
