import { useState, useEffect, useMemo } from 'react';
import toast from 'react-hot-toast';
import {
  HiOutlineDocumentReport,
  HiOutlineDownload,
  HiOutlineClipboardList,
  HiOutlineCube,
  HiOutlineAdjustments,
  HiOutlineReply,
  HiOutlineBookOpen,
  HiOutlineClipboardCheck,
  HiOutlineBan,
  HiOutlineCash,
  HiOutlineChartBar,
  HiOutlineOfficeBuilding,
  HiOutlineFilter,
  HiOutlineCollection,
} from 'react-icons/hi';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';
import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';

// ── PDF helpers ──────────────────────────────────
function addHeader(doc, title, generatedBy, generatedAt) {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('MIZERO INVENTORY HUB', pw / 2, 20, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.text(title, pw / 2, 28, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(80);
  const dateStr = new Date(generatedAt).toLocaleString();
  doc.text(`Generated By: ${generatedBy.full_name}`, 14, 38);
  doc.text(`Role: ${generatedBy.role}`, 14, 43);
  doc.text(`Date: ${dateStr}`, 14, 48);
  return { pw, dateStr };
}

function addFooter(doc, pw, dateStr) {
  const pageCount = doc.internal.getNumberOfPages();
  const pageH = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Signature block on the last page only
    if (i === pageCount) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60);
      doc.text('Checked By: ________________________', 14, pageH - 28);
      doc.text('Approved By: ______________________', 14, pageH - 18);
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text('(Signature)', 14, pageH - 23);
      doc.text('(Signature)', 14, pageH - 13);
    }

    // Page number
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} — Mizero Inventory Hub — ${dateStr}`,
      pw / 2,
      pageH - 8,
      { align: 'center' }
    );
  }
}

function addSummaryTable(doc, label, rows, startY, columnWidths) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(label, 14, startY);

  autoTable(doc, {
    startY: startY + 6,
    body: rows,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: columnWidths || { 0: { cellWidth: 55, fontStyle: 'bold' }, 1: { cellWidth: 40, halign: 'center' } },
    margin: { left: 5, right: 5 },
    tableWidth: 'auto',
  });
}

const fmt = (val) => {
  if (!val && val !== 0) return '0.00';
  return Number(val).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

// ── Format helper ──
const fmtShort = (val) => {
  if (!val && val !== 0) return '0';
  const num = Number(val);
  if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
  if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
  return String(num);
};

// ── Report definitions ──────────────────────────
const REPORTS = [

  // ── DEPARTMENT INTELLIGENCE REPORT ──
  {
    id: 'department-intelligence',
    title: 'Department Inventory Intelligence Report',
    description: 'Advanced department-based inventory analytics: grouped summaries, valuation, low stock analysis, and budget utilization.',
    icon: HiOutlineOfficeBuilding,
    color: 'indigo',
    endpoint: '/reports/department-report',
    filename: 'department-inventory-intelligence-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, departmentSummaries, lowStockItems, valuation, budgetUtilization } = data;
      const { pw, dateStr } = addHeader(doc, 'DEPARTMENT INVENTORY INTELLIGENCE REPORT', generatedBy, generatedAt);
      let yPos = 60;

      // ── SECTION 1: Global Summary ──
      addSummaryTable(doc, '1. GLOBAL SUMMARY', [
        ['Total Items', `${summary.totalItems}`],
        ['Total Stock Quantity', `${summary.totalStock}`],
        ['Total Inventory Value', `${fmt(summary.totalValue)} RWF`],
        ['Categories', `${summary.totalCategories}`],
        ['Low Stock Items', `${summary.lowStockCount}`],
        ['Out of Stock Items', `${summary.outOfStockCount}`],
      ], yPos);
      yPos = doc.lastAutoTable.finalY + 12;

      // ── SECTION 2: Department Summaries ──
      if (departmentSummaries && departmentSummaries.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text('2. DEPARTMENT SUMMARIES', 14, yPos);

        autoTable(doc, {
          startY: yPos + 6,
          head: [['Department', 'Items', 'Total Qty', 'Total Value', 'Low Stock', 'Avg Cost', 'Max Cost']],
          body: departmentSummaries.map(d => [
            String(d.dept_name).substring(0, 30),
            String(d.item_count),
            String(d.total_quantity),
            fmt(d.total_value),
            String(d.low_stock_count),
            fmt(d.avg_unit_cost),
            fmt(d.max_unit_cost),
          ]),
          theme: 'grid',
          headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 7.5, halign: 'center' },
          styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
          columnStyles: {
            0: { cellWidth: 35 }, 1: { cellWidth: 18, halign: 'center' },
            2: { cellWidth: 22, halign: 'center' }, 3: { cellWidth: 30, halign: 'right' },
            4: { cellWidth: 20, halign: 'center' }, 5: { cellWidth: 25, halign: 'right' },
            6: { cellWidth: 25, halign: 'right' },
          },
          margin: { left: 5, right: 5 },
          tableWidth: 'auto',
        });
        yPos = doc.lastAutoTable.finalY + 12;
      }

      // ── SECTION 3: Department Inventory Tables ──
      if (data.departmentItems) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text('3. DEPARTMENT INVENTORY', 14, yPos);
        yPos += 8;

        for (const [deptName, items] of Object.entries(data.departmentItems)) {
          if (yPos > 250) { doc.addPage(); yPos = 20; }

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(10);
          doc.setTextColor(79, 70, 229);
          doc.text(deptName, 14, yPos);

          const rows = items.slice(0, 50).map(item => [
            String(item.sku || '-').substring(0, 15),
            String(item.name || '').substring(0, 35),
            String(item.category || '-').substring(0, 20),
            String(item.quantity),
            String(item.minimum_stock),
            item.unit_cost ? fmt(item.unit_cost) : '-',
            item.quantity === 0 ? 'OUT' : item.quantity <= item.minimum_stock ? 'LOW' : 'OK',
          ]);

          if (items.length > 50) rows.push(['...', `+${items.length - 50} more items`, '', '', '', '', '']);

          autoTable(doc, {
            startY: yPos + 5,
            head: [['SKU', 'Name', 'Category', 'Qty', 'Min', 'Cost', 'Status']],
            body: rows,
            theme: 'grid',
            headStyles: { fillColor: [100, 100, 255], textColor: 255, fontStyle: 'bold', fontSize: 7, halign: 'center' },
            styles: { fontSize: 6.5, cellPadding: 1.5, overflow: 'linebreak' },
            columnStyles: {
              0: { cellWidth: 22 }, 1: { cellWidth: 50 }, 2: { cellWidth: 28 },
              3: { cellWidth: 14, halign: 'center' }, 4: { cellWidth: 14, halign: 'center' },
              5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 16, halign: 'center' },
            },
            didParseCell: (cellData) => {
              if (cellData.section === 'body' && cellData.column.index === 6) {
                const s = cellData.cell.raw;
                if (s === 'OUT') Object.assign(cellData.cell.styles, { fillColor: [254, 202, 202], textColor: [153, 27, 27], fontStyle: 'bold' });
                else if (s === 'LOW') Object.assign(cellData.cell.styles, { fillColor: [254, 243, 199], textColor: [146, 64, 14], fontStyle: 'bold' });
                else Object.assign(cellData.cell.styles, { fillColor: [220, 252, 231], textColor: [22, 101, 52] });
              }
            },
            margin: { left: 5, right: 5 },
            tableWidth: 'auto',
          });
          yPos = doc.lastAutoTable.finalY + 8;
        }
      }
      yPos += 4;

      // ── SECTION 4: Low Stock Analysis ──
      if (yPos > 230) { doc.addPage(); yPos = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text('4. LOW STOCK ANALYSIS', 14, yPos);
      yPos += 8;

      if (!lowStockItems || lowStockItems.length === 0) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('No low stock items found.', 14, yPos);
        yPos += 12;
      } else {
        autoTable(doc, {
          startY: yPos,
          head: [['Department', 'Item Name', 'SKU', 'Qty', 'Min', 'Value', 'Category']],
          body: lowStockItems.map(item => [
            String(item.department_name || '-').substring(0, 25),
            String(item.name || '').substring(0, 35),
            String(item.sku || '-').substring(0, 15),
            String(item.quantity),
            String(item.minimum_stock),
            fmt(item.total_value),
            String(item.category || '-').substring(0, 15),
          ]),
          theme: 'grid',
          headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold', fontSize: 7.5, halign: 'center' },
          styles: { fontSize: 7, cellPadding: 1.5, overflow: 'linebreak' },
          columnStyles: {
            0: { cellWidth: 30 }, 1: { cellWidth: 48 }, 2: { cellWidth: 20 },
            3: { cellWidth: 14, halign: 'center' }, 4: { cellWidth: 14, halign: 'center' },
            5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 22 },
          },
          didParseCell: (cellData) => {
            if (cellData.section === 'body' && cellData.column.index === 3) {
              Object.assign(cellData.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
            }
          },
          margin: { left: 5, right: 5 },
          tableWidth: 'auto',
        });
        yPos = doc.lastAutoTable.finalY + 12;
      }

      // ── SECTION 5: Inventory Valuation ──
      if (yPos > 230) { doc.addPage(); yPos = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text('5. INVENTORY VALUATION', 14, yPos);

      if (valuation && valuation.length > 0) {
        autoTable(doc, {
          startY: yPos + 6,
          head: [['Department', 'Items', 'Total Qty', 'Total Value', 'Avg Cost']],
          body: valuation.map(v => [
            String(v.department_name).substring(0, 30),
            String(v.item_count),
            String(v.total_quantity),
            fmt(v.total_value),
            fmt(v.weighted_avg_cost),
          ]),
          theme: 'grid',
          headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
          styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
          columnStyles: {
            0: { cellWidth: 40 }, 1: { cellWidth: 20, halign: 'center' },
            2: { cellWidth: 25, halign: 'center' }, 3: { cellWidth: 35, halign: 'right' },
            4: { cellWidth: 30, halign: 'right' },
          },
          margin: { left: 5, right: 5 },
          tableWidth: 'auto',
        });
        yPos = doc.lastAutoTable.finalY + 12;
      } else {
        yPos += 12;
      }

      // ── SECTION 6: Budget Utilization ──
      if (yPos > 230) { doc.addPage(); yPos = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text('6. BUDGET UTILIZATION', 14, yPos);

      if (budgetUtilization && budgetUtilization.length > 0) {
        autoTable(doc, {
          startY: yPos + 6,
          head: [['Department', 'Fiscal Year', 'Total Budget', 'Amount Used', 'Remaining', 'Usage %']],
          body: budgetUtilization.map(b => {
            const remaining = Math.max(0, Number(b.total_budget) - Number(b.amount_used));
            const pct = b.total_budget > 0 ? Math.round((b.amount_used / b.total_budget) * 100) : 0;
            return [
              String(b.department_name || '').substring(0, 30),
              String(b.fiscal_year),
              fmt(b.total_budget),
              fmt(b.amount_used),
              fmt(remaining),
              `${pct}%`,
            ];
          }),
          theme: 'grid',
          headStyles: { fillColor: [6, 182, 212], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
          styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
          columnStyles: {
            0: { cellWidth: 35 }, 1: { cellWidth: 22, halign: 'center' },
            2: { cellWidth: 30, halign: 'right' }, 3: { cellWidth: 30, halign: 'right' },
            4: { cellWidth: 30, halign: 'right' }, 5: { cellWidth: 18, halign: 'center' },
          },
          didParseCell: (cellData) => {
            if (cellData.section === 'body' && cellData.column.index === 5) {
              const pct = parseInt(cellData.cell.raw);
              if (pct > 90) Object.assign(cellData.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
              else if (pct > 70) Object.assign(cellData.cell.styles, { textColor: [245, 158, 11], fontStyle: 'bold' });
            }
          },
          margin: { left: 5, right: 5 },
          tableWidth: 'auto',
        });
      } else {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('No budget data available.', 14, yPos + 10);
      }

      addFooter(doc, pw, dateStr);
    },
  },

  // 2. Low Stock Items
  {
    id: 'low-stock-items',
    title: 'Low Stock Items Report',
    description: 'Items with quantity at or below their minimum stock level.',
    icon: HiOutlineBan,
    color: 'amber',
    endpoint: '/reports/inventory-status',
    filename: 'low-stock-items-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, lowStockItems } = data;
      const { pw, dateStr } = addHeader(doc, 'LOW STOCK ITEMS REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Low Stock Items', `${summary.lowStock}`],
        ['Out of Stock Items', `${summary.outOfStock}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text('ITEMS BELOW MINIMUM STOCK', 14, tableY);

      if (!lowStockItems || lowStockItems.length === 0) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('No low stock items found.', 14, tableY + 10);
      } else {
        autoTable(doc, {
          startY: tableY + 6,
          head: [['Item Name', 'Current Quantity', 'Minimum Stock', 'Status']],
          body: lowStockItems.map((item) => [
            String(item.name || '').substring(0, 60),
            String(item.quantity),
            String(item.minimum_stock),
            'LOW',
          ]),
          theme: 'grid',
          headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold', fontSize: 9, halign: 'center' },
          styles: { fontSize: 8, cellPadding: 2.5, overflow: 'linebreak' },
          columnStyles: { 0: { cellWidth: 80 }, 1: { cellWidth: 40, halign: 'center' }, 2: { cellWidth: 40, halign: 'center' }, 3: { cellWidth: 25, halign: 'center' } },
          didParseCell: (data) => {
            if (data.section === 'body' && data.column.index === 3) {
              Object.assign(data.cell.styles, { fillColor: [254, 243, 199], textColor: [146, 64, 14], fontStyle: 'bold' });
            }
          },
          margin: { left: 5, right: 5 },
          tableWidth: 'auto',
        });
      }

      addFooter(doc, pw, dateStr);
    },
  },

  // 3. Stock In
  {
    id: 'stock-in',
    title: 'Stock In Report',
    description: 'All stock-in transactions with supplier details and costs.',
    icon: HiOutlineCube,
    color: 'green',
    endpoint: '/reports/stock-in',
    filename: 'stock-in-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'STOCK IN REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Transactions', `${summary.totalTransactions}`],
        ['Total Quantity', `${summary.totalQuantity}`],
        ['Total Cost', `${Number(summary.totalCost).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Item', 'SKU', 'Qty', 'Unit Price', 'Total Cost', 'Supplier', 'Type', 'Recorded By']],
        body: records.map((r) => [
          new Date(r.date).toLocaleDateString(),
          String(r.item_name || '').substring(0, 40),
          r.item_sku,
          String(r.quantity),
          r.unit_price ? Number(r.unit_price).toLocaleString(undefined, { minimumFractionDigits: 2 }) : '0.00',
          r.total_cost ? Number(r.total_cost).toLocaleString(undefined, { minimumFractionDigits: 2 }) : '0.00',
          String(r.supplier || '-').substring(0, 25),
          r.supplier_type || '-',
          String(r.created_by_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 35 }, 2: { cellWidth: 18 }, 3: { cellWidth: 14, halign: 'center' }, 4: { cellWidth: 22, halign: 'right' }, 5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 25 }, 7: { cellWidth: 20 }, 8: { cellWidth: 22 } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 3. Stock Out
  {
    id: 'stock-out',
    title: 'Stock Out Report',
    description: 'All stock-out transactions with recipient details and costs.',
    icon: HiOutlineClipboardList,
    color: 'red',
    endpoint: '/reports/stock-out',
    filename: 'stock-out-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'STOCK OUT REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Transactions', `${summary.totalTransactions}`],
        ['Total Quantity', `${summary.totalQuantity}`],
        ['Total COGS', `${Number(summary.totalCogs).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Item', 'SKU', 'Qty', 'Recipient', 'Department', 'Reason', 'Recorded By']],
        body: records.map((r) => [
          new Date(r.date).toLocaleDateString(),
          String(r.item_name || '').substring(0, 40),
          r.item_sku,
          String(r.quantity),
          String(r.recipient || '').substring(0, 30),
          String(r.department || '-').substring(0, 25),
          String(r.reason || '-').substring(0, 30),
          String(r.created_by_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 38 }, 2: { cellWidth: 20 }, 3: { cellWidth: 14, halign: 'center' }, 4: { cellWidth: 32 }, 5: { cellWidth: 25 }, 6: { cellWidth: 28 }, 7: { cellWidth: 22 } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 4. Adjustments
  {
    id: 'adjustments',
    title: 'Adjustments Report',
    description: 'All stock adjustments with type, reason, and quantity changes.',
    icon: HiOutlineAdjustments,
    color: 'purple',
    endpoint: '/reports/adjustments',
    filename: 'adjustments-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'ADJUSTMENTS REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Adjustments', `${summary.totalAdjustments}`],
        ['Total Increase', `${summary.totalIncrease}`],
        ['Total Decrease', `${summary.totalDecrease}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Item', 'SKU', 'Type', 'Qty', 'Reason', 'Notes', 'By']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          String(r.item_name || '').substring(0, 40),
          r.item_sku,
          r.adjustment_type === 'increase' ? 'INCREASE' : 'DECREASE',
          String(r.quantity),
          String(r.reason || '-').substring(0, 30),
          String(r.notes || '-').substring(0, 30),
          String(r.created_by_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [147, 51, 234], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 38 }, 2: { cellWidth: 20 }, 3: { cellWidth: 24, halign: 'center' }, 4: { cellWidth: 14, halign: 'center' }, 5: { cellWidth: 28 }, 6: { cellWidth: 28 }, 7: { cellWidth: 22 } },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 3) {
            const type = data.cell.raw;
            if (type === 'INCREASE') Object.assign(data.cell.styles, { textColor: [22, 163, 74] });
            if (type === 'DECREASE') Object.assign(data.cell.styles, { textColor: [220, 38, 38] });
          }
        },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 5. Borrowings
  {
    id: 'borrowings',
    title: 'Borrowings Report',
    description: 'All borrowing transactions with borrower details and status.',
    icon: HiOutlineBookOpen,
    color: 'indigo',
    endpoint: '/reports/borrowings',
    filename: 'borrowings-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'BORROWINGS REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Borrowings', `${summary.totalBorrowings}`],
        ['Total Quantity', `${summary.totalQuantity}`],
        ['Active', `${summary.active}`],
        ['Overdue', `${summary.overdue}`],
        ['Returned', `${summary.returned}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Borrower', 'Phone', 'Item', 'SKU', 'Qty', 'Borrow Date', 'Due Date', 'Status', 'By']],
        body: records.map((r) => [
          String(r.borrower_name || '').substring(0, 25),
          r.borrower_phone || '-',
          String(r.item_name || '').substring(0, 35),
          r.item_sku,
          String(r.quantity),
          new Date(r.borrow_date).toLocaleDateString(),
          new Date(r.due_date).toLocaleDateString(),
          r.status.toUpperCase(),
          String(r.created_by_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 22 }, 2: { cellWidth: 34 }, 3: { cellWidth: 20 }, 4: { cellWidth: 12, halign: 'center' }, 5: { cellWidth: 22 }, 6: { cellWidth: 22 }, 7: { cellWidth: 20, halign: 'center' }, 8: { cellWidth: 22 } },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 7) {
            const status = data.cell.raw;
            if (status === 'OVERDUE') Object.assign(data.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
            else if (status === 'RETURNED') Object.assign(data.cell.styles, { textColor: [22, 163, 74] });
            else if (status === 'BORROWED') Object.assign(data.cell.styles, { textColor: [37, 99, 235] });
          }
        },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 6. Returns
  {
    id: 'returns',
    title: 'Returns Report',
    description: 'All returned borrowing items with condition details.',
    icon: HiOutlineReply,
    color: 'teal',
    endpoint: '/reports/returns',
    filename: 'returns-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'RETURNS REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Returns', `${summary.totalReturns}`],
        ['Total Quantity', `${summary.totalQuantity}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Borrower', 'Item', 'SKU', 'Qty Returned', 'Condition', 'Notes', 'By']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          String(r.borrower_name || '').substring(0, 25),
          String(r.item_name || '').substring(0, 35),
          r.item_sku,
          String(r.returned_quantity),
          r.item_condition || 'good',
          String(r.notes || '-').substring(0, 25),
          String(r.created_by_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 28 }, 2: { cellWidth: 34 }, 3: { cellWidth: 20 }, 4: { cellWidth: 24, halign: 'center' }, 5: { cellWidth: 22, halign: 'center' }, 6: { cellWidth: 25 }, 7: { cellWidth: 22 } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 7. Requests
  {
    id: 'requests',
    title: 'Requests Report',
    description: 'All stock requests with status and review information.',
    icon: HiOutlineClipboardCheck,
    color: 'orange',
    endpoint: '/reports/requests',
    filename: 'requests-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'REQUESTS REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Requests', `${summary.totalRequests}`],
        ['Total Quantity', `${summary.totalQuantity}`],
        ['Pending', `${summary.pending}`],
        ['Approved', `${summary.approved}`],
        ['Allocated', `${summary.allocated}`],
        ['Rejected', `${summary.rejected}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Requester', 'Item', 'SKU', 'Qty', 'Status', 'Justification', 'Reviewer']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          String(r.requester_name || '').substring(0, 25),
          String(r.item_name || '').substring(0, 35),
          r.item_sku,
          String(r.quantity),
          r.status.toUpperCase(),
          String(r.justification || '-').substring(0, 30),
          String(r.reviewer_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 28 }, 2: { cellWidth: 34 }, 3: { cellWidth: 20 }, 4: { cellWidth: 12, halign: 'center' }, 5: { cellWidth: 22, halign: 'center' }, 6: { cellWidth: 28 }, 7: { cellWidth: 22 } },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 5) {
            const s = data.cell.raw;
            if (s === 'ALLOCATED') Object.assign(data.cell.styles, { textColor: [22, 163, 74], fontStyle: 'bold' });
            else if (s === 'REJECTED') Object.assign(data.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
            else if (s === 'PENDING') Object.assign(data.cell.styles, { textColor: [245, 158, 11] });
            else if (s === 'APPROVED') Object.assign(data.cell.styles, { textColor: [37, 99, 235] });
          }
        },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 8. Leftovers
  {
    id: 'leftovers',
    title: 'Leftovers Report',
    description: 'Unused stock returned from issued items.',
    icon: HiOutlineBan,
    color: 'rose',
    endpoint: '/reports/leftovers',
    filename: 'leftovers-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'LEFTOVERS REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Returns', `${summary.totalReturns}`],
        ['Total Quantity Returned', `${summary.totalQuantity}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Item', 'SKU', 'Returned', 'Issued Qty', 'Recipient', 'Notes', 'By']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          String(r.item_name || '').substring(0, 35),
          r.item_sku,
          String(r.returned_quantity),
          String(r.issued_quantity || '-'),
          String(r.recipient || '-').substring(0, 25),
          String(r.notes || '-').substring(0, 25),
          String(r.created_by_name || '-').substring(0, 20),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [225, 29, 72], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 36 }, 2: { cellWidth: 20 }, 3: { cellWidth: 22, halign: 'center' }, 4: { cellWidth: 20, halign: 'center' }, 5: { cellWidth: 28 }, 6: { cellWidth: 25 }, 7: { cellWidth: 22 } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 9. Damage & Loss Liabilities
  {
    id: 'damage-liabilities',
    title: 'Damage & Loss Liabilities Report',
    description: 'All reported liabilities with monetary amounts, payments, and current balances.',
    icon: HiOutlineCash,
    color: 'yellow',
    endpoint: '/reports/damage-liabilities',
    filename: 'damage-loss-liabilities-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'DAMAGE & LOSS LIABILITIES REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Liabilities', `${summary.totalLiabilities}`],
        ['Total Liability Amount', `${Number(summary.totalAmount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Paid', `${Number(summary.totalPaid).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Unpaid', `${summary.unpaid}`],
        ['Partially Paid', `${summary.partiallyPaid}`],
        ['Fully Paid', `${summary.paid}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Type', 'Borrower', 'Item', 'Replacement', 'Liability %', 'Liability Amt', 'Amount Paid', 'Balance', 'Status']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          r.liability_type === 'lost' ? 'LOST' : 'DAMAGED',
          String(r.borrower_name || '-').substring(0, 20),
          String(r.item_name || '-').substring(0, 25),
          Number(r.replacement_cost || r.quantity * r.unit_cost).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          `${r.liability_percentage || 50}%`,
          Number(r.liability_amount || r.total_amount).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_paid || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.balance || r.liability_amount - r.amount_paid || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          (r.status || 'unpaid').replace(/_/g, ' ').toUpperCase(),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [202, 138, 4], textColor: 255, fontStyle: 'bold', fontSize: 7.5, halign: 'center' },
        styles: { fontSize: 7, cellPadding: 1.5, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 18 }, 1: { cellWidth: 18, halign: 'center' }, 2: { cellWidth: 22 }, 3: { cellWidth: 26 }, 4: { cellWidth: 22, halign: 'right' }, 5: { cellWidth: 18, halign: 'center' }, 6: { cellWidth: 22, halign: 'right' }, 7: { cellWidth: 20, halign: 'right' }, 8: { cellWidth: 20, halign: 'right' }, 9: { cellWidth: 22, halign: 'center' } },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 9) {
            const s = data.cell.raw;
            if (s.includes('PAID')) Object.assign(data.cell.styles, { textColor: [22, 163, 74], fontStyle: 'bold' });
            else if (s === 'UNPAID' || s === 'PENDING') Object.assign(data.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
            else if (s.includes('PARTIALLY')) Object.assign(data.cell.styles, { textColor: [245, 158, 11] });
            else if (s === 'WAIVED') Object.assign(data.cell.styles, { textColor: [100, 100, 100] });
          }
          if (data.section === 'body' && data.column.index === 1) {
            const type = data.cell.raw;
            if (type === 'LOST') Object.assign(data.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
            else if (type === 'DAMAGED') Object.assign(data.cell.styles, { textColor: [245, 158, 11], fontStyle: 'bold' });
          }
        },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 10. Damage Report
  {
    id: 'damage-report',
    title: 'Damage Liability Report',
    description: 'Only damaged items where borrower pays 50% of replacement cost.',
    icon: HiOutlineCash,
    color: 'amber',
    endpoint: '/damage-liabilities/reports/damage',
    filename: 'damage-liability-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'DAMAGE LIABILITY REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Damage Cases', `${summary.totalCases}`],
        ['Total Liability', `${Number(summary.totalLiability).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Paid', `${Number(summary.totalPaid).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Balance', `${Number(summary.totalBalance).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Borrower', 'Item', 'Replacement', 'Liability (50%)', 'Paid', 'Balance', 'Status']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          String(r.borrower_name || '-').substring(0, 25),
          String(r.item_name || '-').substring(0, 30),
          Number(r.replacement_cost).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.liability_amount).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_paid || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.balance || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          (r.status || 'pending').replace(/_/g, ' ').toUpperCase(),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 28 }, 2: { cellWidth: 34 }, 3: { cellWidth: 25, halign: 'right' }, 4: { cellWidth: 25, halign: 'right' }, 5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 22, halign: 'right' }, 7: { cellWidth: 24, halign: 'center' } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 11. Loss Report
  {
    id: 'loss-report',
    title: 'Loss Liability Report',
    description: 'Only lost items where borrower pays 100% of replacement cost.',
    icon: HiOutlineCash,
    color: 'red',
    endpoint: '/damage-liabilities/reports/loss',
    filename: 'loss-liability-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'LOSS LIABILITY REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Loss Cases', `${summary.totalCases}`],
        ['Total Replacement', `${Number(summary.totalReplacement).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Liability', `${Number(summary.totalLiability).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Paid', `${Number(summary.totalPaid).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Borrower', 'Item', 'Replacement', 'Liability (100%)', 'Paid', 'Status']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          String(r.borrower_name || '-').substring(0, 25),
          String(r.item_name || '-').substring(0, 30),
          Number(r.replacement_cost).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.liability_amount).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_paid || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          (r.status || 'pending').replace(/_/g, ' ').toUpperCase(),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 28 }, 2: { cellWidth: 34 }, 3: { cellWidth: 25, halign: 'right' }, 4: { cellWidth: 25, halign: 'right' }, 5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 24, halign: 'center' } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 12. Outstanding Liabilities Report
  {
    id: 'outstanding-liabilities',
    title: 'Outstanding Liability Report',
    description: 'All unpaid and partially paid liabilities with remaining balances.',
    icon: HiOutlineCash,
    color: 'orange',
    endpoint: '/damage-liabilities/reports/outstanding',
    filename: 'outstanding-liabilities-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'OUTSTANDING LIABILITIES REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Cases', `${summary.totalCases}`],
        ['Total Liability', `${Number(summary.totalLiability).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Paid', `${Number(summary.totalPaid).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Outstanding', `${Number(summary.totalBalance).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Type', 'Borrower', 'Item', 'Liability', 'Paid', 'Balance', 'Status']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          r.liability_type === 'lost' ? 'LOST' : 'DAMAGED',
          String(r.borrower_name || '-').substring(0, 25),
          String(r.item_name || '-').substring(0, 30),
          Number(r.liability_amount).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_paid || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.balance || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          (r.status || 'pending').replace(/_/g, ' ').toUpperCase(),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [234, 88, 12], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 20, halign: 'center' }, 2: { cellWidth: 28 }, 3: { cellWidth: 34 }, 4: { cellWidth: 25, halign: 'right' }, 5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 22, halign: 'right' }, 7: { cellWidth: 24, halign: 'center' } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 13. Paid Liabilities Report
  {
    id: 'paid-liabilities',
    title: 'Paid Liability Report',
    description: 'All fully paid liabilities with payment dates and amounts.',
    icon: HiOutlineCash,
    color: 'green',
    endpoint: '/damage-liabilities/reports/paid',
    filename: 'paid-liabilities-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'PAID LIABILITIES REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Cases', `${summary.totalCases}`],
        ['Total Liability', `${Number(summary.totalLiability).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Paid', `${Number(summary.totalPaid).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Date', 'Type', 'Borrower', 'Item', 'Liability', 'Paid', 'Paid On']],
        body: records.map((r) => [
          new Date(r.created_at).toLocaleDateString(),
          r.liability_type === 'lost' ? 'LOST' : 'DAMAGED',
          String(r.borrower_name || '-').substring(0, 25),
          String(r.item_name || '-').substring(0, 30),
          Number(r.liability_amount).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_paid || 0).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          r.paid_at ? new Date(r.paid_at).toLocaleDateString() : '-',
        ]),
        theme: 'grid',
        headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 20, halign: 'center' }, 2: { cellWidth: 28 }, 3: { cellWidth: 34 }, 4: { cellWidth: 25, halign: 'right' }, 5: { cellWidth: 25, halign: 'right' }, 6: { cellWidth: 25 } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },

  // 10. Budget
  {
    id: 'budgets',
    title: 'Budget Report',
    description: 'Department budgets with allocated amount, spending, and remaining balance.',
    icon: HiOutlineChartBar,
    color: 'cyan',
    endpoint: '/reports/budgets',
    filename: 'budget-report.pdf',
    generatePdf: async (doc, data) => {
      const { generatedBy, generatedAt, summary, records } = data;
      const { pw, dateStr } = addHeader(doc, 'BUDGET REPORT', generatedBy, generatedAt);

      addSummaryTable(doc, 'SUMMARY', [
        ['Total Budget', `${Number(summary.totalBudget).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Used', `${Number(summary.totalUsed).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
        ['Total Remaining', `${Number(summary.totalRemaining).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
      ], 60);

      const tableY = doc.lastAutoTable.finalY + 12;
      autoTable(doc, {
        startY: tableY + 6,
        head: [['Department', 'Fiscal Year', 'Total Budget', 'Amount Used', 'Remaining', 'Description']],
        body: records.map((r) => [
          String(r.department_name || '').substring(0, 30),
          String(r.fiscal_year),
          Number(r.total_budget).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_used).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          Number(r.amount_remaining).toLocaleString(undefined, { minimumFractionDigits: 2 }),
          String(r.description || '-').substring(0, 40),
        ]),
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
        styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
        columnStyles: { 0: { cellWidth: 35 }, 1: { cellWidth: 22, halign: 'center' }, 2: { cellWidth: 30, halign: 'right' }, 3: { cellWidth: 30, halign: 'right' }, 4: { cellWidth: 30, halign: 'right' }, 5: { cellWidth: 45 } },
        margin: { left: 5, right: 5 },
        tableWidth: 'auto',
      });

      addFooter(doc, pw, dateStr);
    },
  },
];


// ── Color map for card styling ──
const COLOR_STYLES = {
  blue: { bg: 'bg-blue-100', text: 'text-blue-600', btn: 'bg-blue-600 hover:bg-blue-700', header: 'border-blue-200' },
  green: { bg: 'bg-green-100', text: 'text-green-600', btn: 'bg-green-600 hover:bg-green-700', header: 'border-green-200' },
  red: { bg: 'bg-red-100', text: 'text-red-600', btn: 'bg-red-600 hover:bg-red-700', header: 'border-red-200' },
  purple: { bg: 'bg-purple-100', text: 'text-purple-600', btn: 'bg-purple-600 hover:bg-purple-700', header: 'border-purple-200' },
  indigo: { bg: 'bg-indigo-100', text: 'text-indigo-600', btn: 'bg-indigo-600 hover:bg-indigo-700', header: 'border-indigo-200' },
  teal: { bg: 'bg-teal-100', text: 'text-teal-600', btn: 'bg-teal-600 hover:bg-teal-700', header: 'border-teal-200' },
  orange: { bg: 'bg-orange-100', text: 'text-orange-600', btn: 'bg-orange-600 hover:bg-orange-700', header: 'border-orange-200' },
  rose: { bg: 'bg-rose-100', text: 'text-rose-600', btn: 'bg-rose-600 hover:bg-rose-700', header: 'border-rose-200' },
  yellow: { bg: 'bg-yellow-100', text: 'text-yellow-600', btn: 'bg-yellow-600 hover:bg-yellow-700', header: 'border-yellow-200' },
  cyan: { bg: 'bg-cyan-100', text: 'text-cyan-600', btn: 'bg-cyan-600 hover:bg-cyan-700', header: 'border-cyan-200' },
  amber: { bg: 'bg-amber-100', text: 'text-amber-600', btn: 'bg-amber-600 hover:bg-amber-700', header: 'border-amber-200' },
};

// ── Report Card Component ──
function ReportCard({ report, downloading, onDownload }) {
  const styles = COLOR_STYLES[report.color] || COLOR_STYLES.blue;
  const Icon = report.icon;

  return (
    <div className="card p-4 border rounded-lg hover:shadow-md transition-shadow duration-200">
      <div className="flex items-start gap-4">
        <div className={`p-3 ${styles.bg} rounded-lg flex-shrink-0`}>
          <Icon className={`w-8 h-8 ${styles.text}`} />
        </div>
        <div className="flex-1 min-w-0">           <h3 className="text-lg font-semibold truncate" style={{ color: 'var(--text-primary)' }}>{report.title}</h3>
          <p className="text-sm text-gray-500 mt-1">{report.description}</p>
          <button
            onClick={() => onDownload(report)}
            disabled={downloading}
            className={`mt-3 text-white ${styles.btn} disabled:opacity-50 disabled:cursor-not-allowed px-4 py-2 rounded-lg text-sm font-medium inline-flex items-center gap-2 transition-colors duration-150`}
          >
            {downloading ? (
              <>
                <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Downloading...
              </>
            ) : (
              <>
                <HiOutlineDownload className="w-4 h-4" />
                Download PDF
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Department-specific PDF generator ──
const departmentColor = 'teal';
const departmentColorStyles = COLOR_STYLES[departmentColor] || COLOR_STYLES.blue;

async function generateDepartmentPdf(doc, data) {
  const { generatedBy, generatedAt, department, summary, items, lowStockItems, typeBreakdown, movement, budget, recentTransactions } = data;
  const { pw, dateStr } = addHeader(doc, `${department.name} INVENTORY REPORT`, generatedBy, generatedAt);
  let yPos = 60;

  // SECTION 1: Department Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('1. DEPARTMENT SUMMARY', 14, yPos);

  autoTable(doc, {
    startY: yPos + 6,
    body: [
      ['Department', department.name],
      ['Total Items', String(summary.totalItems)],
      ['Total Stock Quantity', String(summary.totalStock)],
      ['Total Inventory Value', `${fmt(summary.totalValue)} RWF`],
      ['Categories', String(summary.totalCategories)],
      ['Low Stock Items', String(summary.lowStockCount)],
      ['Out of Stock Items', String(summary.outOfStockCount)],
    ],
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: { 0: { cellWidth: 50, fontStyle: 'bold' }, 1: { cellWidth: 50, halign: 'center' } },
    margin: { left: 5, right: 5 },
    tableWidth: 'auto',
  });
  yPos = doc.lastAutoTable.finalY + 12;

  // SECTION 2: Inventory Items
  if (yPos > 240) { doc.addPage(); yPos = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('2. INVENTORY ITEMS', 14, yPos);
  yPos += 8;

  if (!items || items.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('No items found in this department.', 14, yPos);
    yPos += 12;
  } else {
    const itemRows = items.slice(0, 50).map(item => [
      String(item.sku || '-').substring(0, 15),
      String(item.name || '').substring(0, 35),
      String(item.category || '-').substring(0, 20),
      String(item.quantity),
      String(item.minimum_stock),
      item.unit_cost ? fmt(item.unit_cost) : '-',
      item.quantity === 0 ? 'OUT' : item.quantity <= item.minimum_stock ? 'LOW' : 'OK',
    ]);

    if (items.length > 50) itemRows.push(['...', `+${items.length - 50} more items`, '', '', '', '', '']);

    autoTable(doc, {
      startY: yPos,
      head: [['SKU', 'Name', 'Category', 'Qty', 'Min', 'Cost', 'Status']],
      body: itemRows,
      theme: 'grid',
      headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: 'bold', fontSize: 7, halign: 'center' },
      styles: { fontSize: 6.5, cellPadding: 1.5, overflow: 'linebreak' },
      columnStyles: {
        0: { cellWidth: 22 }, 1: { cellWidth: 50 }, 2: { cellWidth: 28 },
        3: { cellWidth: 14, halign: 'center' }, 4: { cellWidth: 14, halign: 'center' },
        5: { cellWidth: 22, halign: 'right' }, 6: { cellWidth: 16, halign: 'center' },
      },
      didParseCell: (cellData) => {
        if (cellData.section === 'body' && cellData.column.index === 6) {
          const s = cellData.cell.raw;
          if (s === 'OUT') Object.assign(cellData.cell.styles, { fillColor: [254, 202, 202], textColor: [153, 27, 27], fontStyle: 'bold' });
          else if (s === 'LOW') Object.assign(cellData.cell.styles, { fillColor: [254, 243, 199], textColor: [146, 64, 14], fontStyle: 'bold' });
          else Object.assign(cellData.cell.styles, { fillColor: [220, 252, 231], textColor: [22, 101, 52] });
        }
      },
      margin: { left: 5, right: 5 },
      tableWidth: 'auto',
    });
    yPos = doc.lastAutoTable.finalY + 10;
  }

  // SECTION 3: Low Stock Analysis
  if (yPos > 230) { doc.addPage(); yPos = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('3. LOW STOCK ANALYSIS', 14, yPos);

  if (!lowStockItems || lowStockItems.length === 0) {
    yPos += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('No low stock items found.', 14, yPos);
    yPos += 12;
  } else {
    autoTable(doc, {
      startY: yPos + 6,
      head: [['Item', 'SKU', 'Qty', 'Min Stock', 'Category', 'Value']],
      body: lowStockItems.map(item => [
        String(item.name || '').substring(0, 35),
        String(item.sku || '-').substring(0, 15),
        String(item.quantity),
        String(item.minimum_stock),
        String(item.category || '-'),
        fmt(item.total_value),
      ]),
      theme: 'grid',
      headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
      styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
      columnStyles: {
        0: { cellWidth: 50 }, 1: { cellWidth: 22 }, 2: { cellWidth: 16, halign: 'center' },
        3: { cellWidth: 22, halign: 'center' }, 4: { cellWidth: 22 }, 5: { cellWidth: 22, halign: 'right' },
      },
      didParseCell: (cellData) => {
        if (cellData.section === 'body' && cellData.column.index === 2) {
          Object.assign(cellData.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
        }
      },
      margin: { left: 5, right: 5 },
      tableWidth: 'auto',
    });
    yPos = doc.lastAutoTable.finalY + 10;
  }

  // SECTION 4: Consumables vs Non-Consumables
  if (yPos > 230) { doc.addPage(); yPos = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('4. ITEM TYPE BREAKDOWN', 14, yPos);

  if (typeBreakdown && typeBreakdown.length > 0) {
    autoTable(doc, {
      startY: yPos + 6,
      head: [['Type', 'Items', 'Total Qty', 'Total Value']],
      body: typeBreakdown.map(t => [
        String(t.item_type).charAt(0).toUpperCase() + String(t.item_type).slice(1),
        String(t.item_count),
        String(t.total_quantity),
        fmt(t.total_value),
      ]),
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
      styles: { fontSize: 8, cellPadding: 2.5, overflow: 'linebreak' },
      columnStyles: { 0: { cellWidth: 45 }, 1: { cellWidth: 20, halign: 'center' }, 2: { cellWidth: 25, halign: 'center' }, 3: { cellWidth: 35, halign: 'right' } },
      margin: { left: 5, right: 5 },
      tableWidth: 'auto',
    });
    yPos = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('No type breakdown data available.', 14, yPos + 10);
    yPos += 18;
  }

  // SECTION 5: Stock Movement Summary
  if (yPos > 230) { doc.addPage(); yPos = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('5. STOCK MOVEMENT SUMMARY', 14, yPos);

  autoTable(doc, {
    startY: yPos + 6,
    body: [
      ['Stock In Transactions', String(movement.stock_in_count)],
      ['Stock In Quantity', String(movement.stock_in_qty)],
      ['Stock In Cost', `${fmt(movement.stock_in_cost)} RWF`],
      ['Stock Out Transactions', String(movement.stock_out_count)],
      ['Stock Out Quantity', String(movement.stock_out_qty)],
      ['Stock Out COGS', `${fmt(movement.stock_out_cogs)} RWF`],
    ],
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: { 0: { cellWidth: 55, fontStyle: 'bold' }, 1: { cellWidth: 40, halign: 'center' } },
    margin: { left: 5, right: 5 },
    tableWidth: 'auto',
  });
  yPos = doc.lastAutoTable.finalY + 10;

  // SECTION 6: Budget Utilization
  if (yPos > 230) { doc.addPage(); yPos = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('6. BUDGET UTILIZATION', 14, yPos);

  if (budget && budget.total_budget > 0) {
    const remaining = Math.max(0, Number(budget.total_budget) - Number(budget.amount_used));
    const pct = budget.total_budget > 0 ? Math.round((budget.amount_used / budget.total_budget) * 100) : 0;

    autoTable(doc, {
      startY: yPos + 6,
      body: [
        ['Fiscal Year', String(budget.fiscal_year)],
        ['Total Budget', `${fmt(budget.total_budget)} RWF`],
        ['Amount Used', `${fmt(budget.amount_used)} RWF`],
        ['Remaining', `${fmt(remaining)} RWF`],
        ['Usage', `${pct}%`],
      ],
      theme: 'grid',
      styles: { fontSize: 8.5, cellPadding: 3, overflow: 'linebreak' },
      columnStyles: { 0: { cellWidth: 50, fontStyle: 'bold' }, 1: { cellWidth: 50, halign: 'center' } },
      didParseCell: (cellData) => {
        if (cellData.section === 'body' && cellData.column.index === 1) {
          const raw = cellData.cell.raw;
          if (typeof raw === 'string' && raw.includes('%')) {
            const pctVal = parseInt(raw);
            if (pctVal > 90) Object.assign(cellData.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
            else if (pctVal > 70) Object.assign(cellData.cell.styles, { textColor: [245, 158, 11], fontStyle: 'bold' });
          }
        }
      },
      margin: { left: 5, right: 5 },
      tableWidth: 'auto',
    });
    yPos = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('No budget data available for this department.', 14, yPos + 10);
    yPos += 18;
  }

  // SECTION 7: Recent Transactions
  if (yPos > 230) { doc.addPage(); yPos = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('7. RECENT TRANSACTIONS', 14, yPos);

  if (recentTransactions && recentTransactions.length > 0) {
    autoTable(doc, {
      startY: yPos + 6,
      head: [['Date', 'Type', 'Item', 'Qty', 'Amount', 'By']],
      body: recentTransactions.map(t => [
        new Date(t.date).toLocaleDateString(),
        t.type,
        String(t.item_name || '').substring(0, 35),
        String(t.quantity),
        fmt(t.total_cost),
        String(t.user_name || '-').substring(0, 20),
      ]),
      theme: 'grid',
      headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: 'bold', fontSize: 8, halign: 'center' },
      styles: { fontSize: 7.5, cellPadding: 2, overflow: 'linebreak' },
      columnStyles: {
        0: { cellWidth: 22 }, 1: { cellWidth: 24, halign: 'center' }, 2: { cellWidth: 50 },
        3: { cellWidth: 14, halign: 'center' }, 4: { cellWidth: 22, halign: 'right' }, 5: { cellWidth: 22 },
      },
      didParseCell: (cellData) => {
        if (cellData.section === 'body' && cellData.column.index === 1) {
          if (cellData.cell.raw === 'Stock In') Object.assign(cellData.cell.styles, { textColor: [22, 163, 74], fontStyle: 'bold' });
          if (cellData.cell.raw === 'Stock Out') Object.assign(cellData.cell.styles, { textColor: [220, 38, 38], fontStyle: 'bold' });
        }
      },
      margin: { left: 5, right: 5 },
      tableWidth: 'auto',
    });
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('No recent transactions for this department.', 14, yPos + 10);
  }

  addFooter(doc, pw, dateStr);
}

// ── Department Report Card Component ──
function DepartmentReportCard({ department, downloading, onDownload }) {
  const styles = departmentColorStyles;

  return (
    <div className="card p-4 border rounded-lg hover:shadow-md transition-shadow duration-200 hover:border-teal-300">
      <div className="flex items-start gap-4">
        <div className={`p-3 ${styles.bg} rounded-lg flex-shrink-0`}>
          <HiOutlineOfficeBuilding className={`w-8 h-8 ${styles.text}`} />
        </div>
        <div className="flex-1 min-w-0">
          <h3 className="text-lg font-semibold truncate" style={{ color: 'var(--text-primary)' }}>{department.name}</h3>
          <p className="text-sm text-gray-500 mt-1">Inventory analytics and valuation for {department.name}.</p>
          <button
            onClick={() => onDownload(department)}
            disabled={downloading}
            className={`mt-3 text-white ${styles.btn} disabled:opacity-50 disabled:cursor-not-allowed px-4 py-2 rounded-lg text-sm font-medium inline-flex items-center gap-2 transition-colors duration-150`}
          >
            {downloading ? (
              <>
                <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Downloading...
              </>
            ) : (
              <>
                <HiOutlineDownload className="w-4 h-4" />
                Download PDF
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Main Page ──
export default function Reports() {
  const { user } = useAuth();
  const [downloadingId, setDownloadingId] = useState(null);
  const [departments, setDepartments] = useState([]);
  const [showFilters, setShowFilters] = useState(false);
  const [filters, setFilters] = useState({ department_id: '', item_type: '', low_stock: '' });

  useEffect(() => {
    fetchDepartments();
  }, []);

  const fetchDepartments = async () => {
    try {
      const { data } = await api.get('/departments');
      setDepartments(data);
    } catch {}
  };

  const handleDownload = async (report) => {
    setDownloadingId(report.id);

    try {
      // Build filter params
      const params = {};
      if (filters.department_id) params.department_id = filters.department_id;

      const { data } = await api.get(report.endpoint, { params });
      const doc = new jsPDF('landscape', 'mm', 'a4');
      await report.generatePdf(doc, data);
      doc.save(report.filename);
      toast.success(`${report.title} downloaded successfully`);
    } catch (error) {
      toast.error(error.response?.data?.message || `Failed to download ${report.title}`);
    } finally {
      setDownloadingId(null);
    }
  };

  // Filter departments based on user role
  const visibleDepartments = useMemo(() => {
    if (user.role_name === 'staff') {
      const userDeptIds = user.department_ids || [];
      return departments.filter(d => userDeptIds.includes(d.id));
    }
    return departments;
  }, [departments, user]);

  // Department download handler
  const handleDepartmentDownload = async (dept) => {
    const downloadId = `dept-${dept.id}`;
    setDownloadingId(downloadId);

    try {
      const { data } = await api.get(`/reports/department/${dept.id}`);
      const doc = new jsPDF('landscape', 'mm', 'a4');
      await generateDepartmentPdf(doc, data);
      doc.save(`${dept.name.replace(/\s+/g, '-')}-inventory-report.pdf`);
      toast.success(`${dept.name} report downloaded successfully`);
    } catch (error) {
      toast.error(error.response?.data?.message || `Failed to download ${dept.name} report`);
    } finally {
      setDownloadingId(null);
    }
  };

  // Filtered inventory-type reports (first 2: flat + dept)
  const inventoryReports = REPORTS.slice(0, 2);
  const otherReports = REPORTS.slice(2);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>Reports</h1>
          <p className="text-sm text-gray-500 mt-1">Download comprehensive PDF reports for all inventory operations.</p>
        </div>
      </div>

      {/* ── Filter Panel ── */}
      <div className="card">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <HiOutlineFilter className="w-5 h-5" style={{ color: 'var(--primary)' }} />
            <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Report Filters</span>
          </div>
          <button
            onClick={() => setShowFilters(!showFilters)}
            className="btn-secondary text-sm"
            style={showFilters ? { backgroundColor: 'rgba(139, 158, 255, 0.1)', color: 'var(--primary)' } : {}}
          >
            {showFilters ? 'Hide Filters' : 'Show Filters'}
          </button>
        </div>

        {showFilters && (
          <div className="flex flex-wrap gap-4 mt-4">
            <div>
              <label className="block text-xs font-semibold mb-1" style={{ color: 'var(--text-muted)' }}>Department</label>
              <select
                className="form-input w-auto min-w-[200px]"
                value={filters.department_id}
                onChange={(e) => setFilters({ ...filters, department_id: e.target.value })}
              >
                <option value="">All Departments</option>
                {departments.map((d) => (
                  <option key={d.id} value={d.id}>{d.name}</option>
                ))}
              </select>
            </div>
            <div className="flex items-end gap-2">
              {(filters.department_id || filters.item_type || filters.low_stock) && (
                <button
                  onClick={() => setFilters({ department_id: '', item_type: '', low_stock: '' })}
                  className="btn-secondary text-sm"
                >
                  Clear Filters
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      {/* ── INVENTORY REPORTS SECTION ── */}
      <div>
        <h2 className="text-lg font-bold mb-3 flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
          <HiOutlineCube className="w-5 h-5" style={{ color: 'var(--primary)' }} />
          Inventory Reports
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {inventoryReports.map((report) => (
            <ReportCard
              key={report.id}
              report={report}
              downloading={downloadingId === report.id}
              onDownload={handleDownload}
            />
          ))}
        </div>
      </div>

      {/* ── TRANSACTION & FINANCIAL REPORTS ── */}
      <div>
        <h2 className="text-lg font-bold mb-3 flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
          <HiOutlineClipboardList className="w-5 h-5" style={{ color: 'var(--primary)' }} />
          Transaction & Financial Reports
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {otherReports.map((report) => (
            <ReportCard
              key={report.id}
              report={report}
              downloading={downloadingId === report.id}
              onDownload={handleDownload}
            />
          ))}
        </div>
      </div>

      {/* ── DEPARTMENT REPORTS ── */}
      {(user.role_name === 'super_admin' || user.role_name === 'admin' || user.role_name === 'stock_manager' || (user.role_name === 'staff' && visibleDepartments.length > 0)) && (
        <div>
          <h2 className="text-lg font-bold mb-3 flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
            <HiOutlineCollection className="w-5 h-5" style={{ color: 'var(--primary)' }} />
            Department Reports
          </h2>
          <p className="text-sm text-gray-500 mb-4">
            Generate department-specific inventory analytics and valuation reports with one click.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {visibleDepartments.map((dept) => (
              <DepartmentReportCard
                key={dept.id}
                department={dept}
                downloading={downloadingId === `dept-${dept.id}`}
                onDownload={handleDepartmentDownload}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
