-- ============================================
-- Mizero Inventory Hub - Seed Data
-- ============================================
-- Password for all users: password123
-- ============================================

USE mizero_inventory;

-- Insert departments
INSERT INTO departments (name, description) VALUES
('General Store', 'Main inventory storage'),
('IT Department', 'Information technology equipment'),
('Human Resources', 'HR department supplies'),
('Finance', 'Finance department'),
('Operations', 'Operations and logistics');

-- Insert users (password: password123 / real bcrypt hash generated by bcryptjs)
INSERT INTO users (full_name, email, password, role_id, department_id, status) VALUES
('Super Admin', 'admin@mizero.com', '$2a$12$cpRzUxtYqwC6s1pFJ/zXOuJQgl35veyz6ZNIna9auydN7.J3dL3Im', 1, NULL, 'active'),
('John Stock Manager', 'john@mizero.com', '$2a$12$cpRzUxtYqwC6s1pFJ/zXOuJQgl35veyz6ZNIna9auydN7.J3dL3Im', 4, 2, 'active'),
('Sarah Stock', 'stock@mizero.com', '$2a$12$cpRzUxtYqwC6s1pFJ/zXOuJQgl35veyz6ZNIna9auydN7.J3dL3Im', 4, 1, 'active'),
('Mike Staff', 'staff@mizero.com', '$2a$12$cpRzUxtYqwC6s1pFJ/zXOuJQgl35veyz6ZNIna9auydN7.J3dL3Im', 4, 3, 'active');

-- Update department managers
-- Stock manager assigned as department manager
UPDATE departments SET manager_id = 3 WHERE id = 2;
UPDATE departments SET manager_id = 3 WHERE id = 1;

-- Insert sample categories of items
INSERT INTO items (sku, name, description, category, unit, quantity, minimum_stock, item_type, department_id, created_by) VALUES
('INV-A001-0001', 'Office Paper A4', 'Standard A4 copy paper 80gsm', 'Office Supplies', 'ream', 150, 20, 'consumable', 3, 1),
('INV-A001-0002', 'Ballpoint Pens Blue', 'Blue ink ballpoint pens box of 50', 'Office Supplies', 'box', 80, 10, 'consumable', 3, 1),
('INV-B002-0001', 'Dell Laptop Latitude 3420', 'Business laptop 8GB RAM 256GB SSD', 'Electronics', 'pcs', 15, 5, 'non-consumable', 2, 1),
('INV-B002-0002', 'HP LaserJet Printer', 'Monochrome laser printer', 'Electronics', 'pcs', 8, 2, 'non-consumable', 2, 1),
('INV-C003-0001', 'Cleaning Detergent 5L', 'Multi-surface cleaning detergent', 'Cleaning', 'bottle', 40, 10, 'consumable', 5, 1),
('INV-C003-0002', 'Paper Towels', 'Industrial paper towel rolls', 'Cleaning', 'roll', 200, 30, 'consumable', 5, 1),
('INV-D004-0001', 'Office Chair', 'Ergonomic office chair', 'Furniture', 'pcs', 25, 5, 'non-consumable', 1, 1),
('INV-D004-0002', 'Whiteboard 120x90cm', 'Magnetic whiteboard with markers', 'Furniture', 'pcs', 12, 3, 'non-consumable', 1, 1);

-- Insert sample stock in records
INSERT INTO stock_in (item_id, quantity, supplier, reference_number, notes, date, created_by) VALUES
(1, 200, 'OfficeMax Supplies', 'PO-2024-001', 'Monthly office supplies order', '2024-01-15', 1),
(2, 100, 'OfficeMax Supplies', 'PO-2024-001', 'Monthly office supplies order', '2024-01-15', 1),
(3, 20, 'Dell Technologies', 'PO-2024-002', 'Q1 hardware procurement', '2024-01-20', 1),
(4, 10, 'HP Direct', 'PO-2024-003', 'Printer replacement program', '2024-01-25', 1);

-- Insert sample stock out records
INSERT INTO stock_out (item_id, quantity, recipient, department, reason, date, created_by) VALUES
(1, 30, 'HR Department', 'Human Resources', 'Monthly usage', '2024-02-01', 3),
(2, 15, 'Finance Team', 'Finance', 'Office supplies', '2024-02-01', 3),
(3, 3, 'Alice Johnson', 'IT Department', 'New employee setup', '2024-02-05', 3);

-- Insert sample borrowings
INSERT INTO borrowings (item_id, borrower_name, borrower_phone, quantity, borrow_date, due_date, status, created_by) VALUES
(3, 'Bob Williams', '+250788123456', 1, '2024-02-10', '2024-02-24', 'borrowed', 3),
(4, 'Carol Davis', '+250788654321', 1, '2024-02-12', '2024-02-26', 'borrowed', 3);

-- Insert sample requests
INSERT INTO requests (requester_id, item_id, quantity, justification, status) VALUES
(4, 1, 10, 'Need paper for monthly reports', 'pending'),
(4, 2, 5, 'Office pens running low', 'approved'),
(4, 3, 1, 'Need laptop for new intern', 'pending');

-- Insert sample activity logs
INSERT INTO activity_logs (user_id, action, module, description) VALUES
(1, 'login', 'auth', 'Super Admin logged in'),
(1, 'create', 'inventory', 'Created sample inventory items'),
(3, 'stock_in', 'inventory', 'Stock in: 200 reams of Office Paper A4'),
(3, 'stock_out', 'inventory', 'Stock out: 30 reams to HR Department');

-- Insert sample notifications
INSERT INTO notifications (user_id, title, message, module, reference_id) VALUES
(1, 'Welcome to Mizero Hub', 'Your inventory management system is ready to use.', 'system', NULL),
(2, 'Low Stock Alert', 'Item Dell Laptop Latitude 3420 has low stock.', 'inventory', 3),
(3, 'New Request', 'Mike Staff requested 10 of Office Paper A4', 'requests', 1);

-- ============================================
-- Default password for all seeded users: password123
-- ============================================
